-- AlterTable
ALTER TABLE "Episode" ALTER COLUMN "dateAired" SET DEFAULT '01/01/1990',
ALTER COLUMN "dateAired" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Season" ALTER COLUMN "dateAired" SET DEFAULT '01/01/1990',
ALTER COLUMN "dateAired" SET DATA TYPE TEXT;
