/*
  Warnings:

  - A unique constraint covering the columns `[userName]` on the table `User` will be added. If there are existing duplicate values, this will fail.

*/
-- AlterTable
ALTER TABLE "Actor" ALTER COLUMN "fullname" DROP NOT NULL,
ALTER COLUMN "fullname" DROP DEFAULT,
ALTER COLUMN "debut" DROP NOT NULL,
ALTER COLUMN "debut" DROP DEFAULT,
ALTER COLUMN "description" DROP NOT NULL,
ALTER COLUMN "description" DROP DEFAULT,
ALTER COLUMN "photoSrc" DROP NOT NULL,
ALTER COLUMN "photoSrc" DROP DEFAULT,
ALTER COLUMN "photoSrcProd" DROP NOT NULL,
ALTER COLUMN "photoSrcProd" DROP DEFAULT;

-- AlterTable
ALTER TABLE "ActorReview" ALTER COLUMN "content" DROP NOT NULL,
ALTER COLUMN "content" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Crew" ALTER COLUMN "fullname" DROP NOT NULL,
ALTER COLUMN "fullname" DROP DEFAULT,
ALTER COLUMN "photoSrc" DROP NOT NULL,
ALTER COLUMN "photoSrc" DROP DEFAULT,
ALTER COLUMN "role" DROP NOT NULL,
ALTER COLUMN "role" DROP DEFAULT,
ALTER COLUMN "photoSrcProd" DROP NOT NULL,
ALTER COLUMN "photoSrcProd" DROP DEFAULT,
ALTER COLUMN "description" DROP NOT NULL,
ALTER COLUMN "description" DROP DEFAULT,
ALTER COLUMN "debut" DROP NOT NULL,
ALTER COLUMN "debut" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Episode" ALTER COLUMN "title" DROP NOT NULL,
ALTER COLUMN "title" DROP DEFAULT,
ALTER COLUMN "photoSrc" DROP NOT NULL,
ALTER COLUMN "photoSrc" DROP DEFAULT,
ALTER COLUMN "photoSrcProd" DROP NOT NULL,
ALTER COLUMN "photoSrcProd" DROP DEFAULT,
ALTER COLUMN "description" DROP NOT NULL,
ALTER COLUMN "description" DROP DEFAULT,
ALTER COLUMN "dateAired" DROP NOT NULL,
ALTER COLUMN "dateAired" DROP DEFAULT,
ALTER COLUMN "duration" DROP NOT NULL,
ALTER COLUMN "duration" DROP DEFAULT,
ALTER COLUMN "trailerSrc" DROP NOT NULL,
ALTER COLUMN "trailerSrc" DROP DEFAULT,
ALTER COLUMN "ratingImdb" DROP NOT NULL,
ALTER COLUMN "ratingImdb" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Genre" ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "name" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Message" ALTER COLUMN "text" DROP NOT NULL,
ALTER COLUMN "text" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Movie" ALTER COLUMN "title" DROP NOT NULL,
ALTER COLUMN "title" DROP DEFAULT,
ALTER COLUMN "photoSrc" DROP NOT NULL,
ALTER COLUMN "photoSrc" DROP DEFAULT,
ALTER COLUMN "photoSrcProd" DROP NOT NULL,
ALTER COLUMN "photoSrcProd" DROP DEFAULT,
ALTER COLUMN "trailerSrc" DROP NOT NULL,
ALTER COLUMN "trailerSrc" DROP DEFAULT,
ALTER COLUMN "ratingImdb" DROP NOT NULL,
ALTER COLUMN "ratingImdb" DROP DEFAULT,
ALTER COLUMN "description" DROP NOT NULL,
ALTER COLUMN "description" DROP DEFAULT,
ALTER COLUMN "dateAired" DROP NOT NULL,
ALTER COLUMN "dateAired" DROP DEFAULT,
ALTER COLUMN "duration" DROP NOT NULL,
ALTER COLUMN "duration" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Notification" ALTER COLUMN "type" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Season" ALTER COLUMN "title" DROP NOT NULL,
ALTER COLUMN "title" DROP DEFAULT,
ALTER COLUMN "photoSrc" DROP NOT NULL,
ALTER COLUMN "photoSrc" DROP DEFAULT,
ALTER COLUMN "photoSrcProd" DROP NOT NULL,
ALTER COLUMN "photoSrcProd" DROP DEFAULT,
ALTER COLUMN "ratingImdb" DROP NOT NULL,
ALTER COLUMN "ratingImdb" DROP DEFAULT,
ALTER COLUMN "serieId" DROP DEFAULT,
ALTER COLUMN "dateAired" DROP NOT NULL,
ALTER COLUMN "dateAired" DROP DEFAULT,
ALTER COLUMN "trailerSrc" DROP NOT NULL,
ALTER COLUMN "trailerSrc" DROP DEFAULT,
ALTER COLUMN "description" DROP NOT NULL,
ALTER COLUMN "description" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Serie" ALTER COLUMN "title" DROP NOT NULL,
ALTER COLUMN "title" DROP DEFAULT,
ALTER COLUMN "photoSrc" DROP NOT NULL,
ALTER COLUMN "photoSrc" DROP DEFAULT,
ALTER COLUMN "photoSrcProd" DROP NOT NULL,
ALTER COLUMN "photoSrcProd" DROP DEFAULT,
ALTER COLUMN "trailerSrc" DROP NOT NULL,
ALTER COLUMN "trailerSrc" DROP DEFAULT,
ALTER COLUMN "description" DROP NOT NULL,
ALTER COLUMN "description" DROP DEFAULT,
ALTER COLUMN "ratingImdb" DROP NOT NULL,
ALTER COLUMN "ratingImdb" DROP DEFAULT,
ALTER COLUMN "dateAired" DROP NOT NULL,
ALTER COLUMN "dateAired" DROP DEFAULT;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "bio" DROP NOT NULL,
ALTER COLUMN "bio" DROP DEFAULT;

-- CreateIndex
CREATE UNIQUE INDEX "User_userName_key" ON "User"("userName");
