export const movies = [
    {
        title: 'Freaks Out (2021)',
        trailerSrc: 'https://www.youtube.com/embed/D8La5G1DzCM',
        duration: '141 min',
        releaseYear: 2021,
        ratingImdb: 7.4,
        description:
            'Matilde, Cencio, Fulvio dhe Mario janë të bashkuar kur Lufta e Dytë Botërore godet Romën. Izraeli, pronari i cirkut të tyre, zhduket në përpjekje për të gjetur një vend jashtë shtetit për të gjithë. ',
        photoSrc: 'http://localhost:4000/images/movies/1TkkTo8UiRl5lWM5qkAISHXg0fU.jpg',
    },

    {
        title: 'My Father&#8217;s Violin (2022) a.k.a Babamin Kemani',
        trailerSrc: 'https://www.youtube.com/embed/GAmo87Ep-tI',
        duration: '112 min',
        releaseYear: 2022,
        ratingImdb: 6.5,
        description:
            'Përmes pikëllimit të tyre të përbashkët dhe lidhjes me muzikën, një vajzë jetime lidhet me xhaxhain e saj violinist të suksesshëm emocionalisht të përmbajtur. ',
        photoSrc:
            'http://localhost:4000/images/movies/AAAABUDmZc0IlYhKxh_DwvPU7qvpsrbSoCgyCEq-B_W552mUo5Qd6IYm9cf6WdfcyfccLK3qumrjgGbpid6I72Y4CVi-eVA-sy8XRgUxF4I41MOefi0gwN-mAYog9fhe1g.jpg',
    },
    {
        title: 'The Invisible Guest (2016) a.k.a Contratiempo',
        trailerSrc: 'https://www.youtube.com/embed/epCg2RbyF80',
        duration: '126 min',
        releaseYear: 2016,
        ratingImdb: 8.1,
        description:
            'Nje biznesmen i ri perballet me nje avokat ne perpjekje per te provuar pafajesine per vrasjen e te dashures se tij.',
        photoSrc: 'http://localhost:4000/images/movies/8c9fce3c0ffa46576423d44b525447edc25f1396.jpg',
    },
    {
        title: 'Blood and Bone (2009)',
        trailerSrc: 'https://www.youtube.com/embed/KyOtQr5u-uY',
        duration: '93 min',
        releaseYear: 2009,
        ratingImdb: 6.7,
        description:
            'Ish i dënuari Boun është forca e re në skenën e ndeshjeve të fshehta te rrugëve në Los Anxheles. Kur ai mund kampionin në fuqi, bosi i gangsterëve vendas dëshiron që ta fusë Bounin në një seri ndeshjesh ndërkombëtare me fitime të mëdha. Refuzimi i Bounit nis një shfaqje shpërthyese midis dy armiqve të fuqishëm që po rrezikojnë gjithçka.',
        photoSrc: 'http://localhost:4000/images/movies/5254_1_ladsfgfdgdfgdfgfdgfdgrge.jpg',
    },
    {
        title: 'Spider-Man: No Way Home (2021)',
        trailerSrc: 'https://www.youtube.com/embed/JfVOs4VSpmA',
        duration: '148 min',
        releaseYear: 2021,
        ratingImdb: 8.7,
        description:
            'Peter Parker është i demaskuar dhe nuk është më në gjendje të ndajë jetën e tij normale nga rreziku i të qenit një Super Hero. Kur ai kërkon ndihmë nga Doctor Strange, rreziku shtohet, duke e detyruar atë të zbulojë se çfarë do të thotë me të vërtetë të jesh Spider-Man.',
        photoSrc: 'http://localhost:4000/images/movies/1gxZrx9gL9ov2c1NpXimEUzMTmh.jpg',
    },
    {
        title: 'Iron Will (1994)',
        trailerSrc: 'https://www.youtube.com/embed/giLeHfkJeXU',
        duration: '108 min',
        releaseYear: 1994,
        ratingImdb: 6.6,
        description:
            "Pas vdekjes së babait të tij, përgjegjësia për t'u kujdesur për familjen bie mbi supet e Will. Ai merr pjesë në një garë me qen, e cila kërkon orë të gjata garash dhe një vullnet të hekurt për të fituar. ",
        photoSrc: 'http://localhost:4000/images/movies/6Ujbtp0NklUoQ67s32HyW6R5540.jpg',
    },
    {
        title: 'Panama (2022)',
        trailerSrc: 'https://www.youtube.com/embed/2GSzkfe1aAY',
        duration: '94 min',
        releaseYear: 2022,
        ratingImdb: 0,
        description:
            'Një ish-marins punësohet nga një kontraktues i mbrojtjes për të udhëtuar në Panama për të mbyllur një marrëveshje armësh. Në këtë proces ai përfshihet me pushtimin e Panamasë nga SHBA dhe nxjerr një mësim të rëndësishëm për natyrën e vërtetë të pushtetit politik. ',
        photoSrc: 'http://localhost:4000/images/movies/82I3tDsGDTMy7lHar84Gz0jUuyW.jpg',
    },
    {
        title: 'Eternals (2021)',
        trailerSrc: 'https://www.youtube.com/embed/x_me3xsvDgk',
        duration: '156 min',
        releaseYear: 2021,
        ratingImdb: 6.8,
        description:
            'Të përjetshmit janë një skuadër jashtëtokësorësh të lashtë që kanë jetuar në Tokë në fshehtësi për mijëra vjet. Kur një tragjedi e papritur i detyron të dalin nga hija, ata duhet të ribashkohen kundër armikut më të lashtë të njerëzimit…',
        photoSrc: 'http://localhost:4000/images/movies/1RjyfPLsZTq3lUdJY7pTzcmpPKl.jpg',
    },
    {
        title: 'Money Trap (2019) a.k.a. Organize Isler: Sazan Sarmali',
        trailerSrc: 'https://www.youtube.com/embed/gcH0KPQVVH4',
        duration: '121 min',
        releaseYear: 2019,
        ratingImdb: 6,
        description:
            "Asim Noyan mashtron njerëzit me gënjeshtrat dhe lojërat e tij. Asim Noyan-i dhe banda e tij, të cilët askush tjetër nuk ka mundur t'i kapë, ngatërrohet përsëri në një mashtrim. ",
        photoSrc: 'http://localhost:4000/images/movies/4kiVg3QJQghjtRupyfWYI3T1R0O-1.jpg',
    },
    {
        title: 'Inch&#8217;Allah (2012)',
        trailerSrc: 'https://www.youtube.com/embed/53XLPquQD6Q',
        duration: '102 min',
        releaseYear: 2012,
        ratingImdb: 6.8,
        description:
            'Një mjeke kanadeze i gjen simpatitë e saj të testuara rëndë ndërsa punonte në territoret palestineze të shkatërruara nga konflikti. ',
        photoSrc: 'http://localhost:4000/images/movies/9BCd5LdVHQmWqEnDTJ5Ut8idstP-1.jpg',
    },
    {
        title: 'Mobile Suit Gundam: Hathaway (2021)',
        trailerSrc: 'https://www.youtube.com/embed/MzxnPP5TLeU',
        duration: '95 min',
        releaseYear: 2021,
        ratingImdb: 6.6,
        description:
            'Hathauej Noa, bëhet pjesë e një organizate terroriste e quajtur Mufti i cili organizon një sulm ndaj ministrave të Federatës së Tokës. ',
        photoSrc: 'http://localhost:4000/images/movies/6gw8onh4FKsruBA7Oouv01EFxzn-1.jpg',
    },
    {
        title: 'Rescued by Ruby (2022)',
        trailerSrc: 'https://www.youtube.com/embed/-Pwxr307O4w',
        duration: '90 min',
        releaseYear: 2022,
        ratingImdb: 7.3,
        description:
            "Duke ndjekur ëndrrën e tij për t'u bashkuar me njësinë elitare të K-9, një ushtarak i shtetit bashkëpunon me një qen strehe shumë të zgjuar por të pabindur, Rubin. ",
        photoSrc:
            'http://localhost:4000/images/movies/AAAABRFlUGzasg1we4oVLLc9JXVq7ZSQLn7HdWN843xQeoxnJ-Ls416_Fd9MxwwWpQRVluHj3dYxFCFqxorgsuRN1eG8U8KnhpwcWXWV8z8d_BRv7u-_8SNe_1qEByE-Ow.jpg',
    },
    {
        title: 'The Girl on the Mountain (2022)',
        trailerSrc: 'https://www.youtube.com/embed/Y0vh8jQ7HMQ',
        duration: '94 min',
        releaseYear: 2022,
        ratingImdb: 6.4,
        description:
            "Kur një pylltar i izoluar gjen një vajzë të vogël memece që endet vetëm në pyll, ai duhet ta mbrojë atë nga forcat e liga të vendosura për t'i dhënë fund jetës së saj. ",
        photoSrc: 'http://localhost:4000/images/movies/1ZiZ3eVUWPxJROTkYbH8FBC9UuB.jpg',
    },
    {
        title: 'The Weekend Away (2022)',
        trailerSrc: 'https://www.youtube.com/embed/XpfjN-7Hf-8',
        duration: '89 min',
        releaseYear: 2022,
        ratingImdb: 5.6,
        description:
            'Një fundjavë pushimi në Kroaci shkon keq kur një grua akuzohet për vrasjen e shoqes së saj më të mirë. Ndërsa përpiqet të pastrojë emrin e saj dhe të zbulojë të vërtetën, përpjekjet e saj zbulojnë një sekret të dhimbshëm. ',
        photoSrc: 'http://localhost:4000/images/movies/6MS0QEl7UK2gdFFbHfNwuYlsq4H.jpg',
    },
    {
        title: 'Black Crab (2022) a.k.a. Svart krabba',
        trailerSrc: 'https://www.youtube.com/embed/fmjKsL_-rfw',
        duration: '114 min',
        releaseYear: 2022,
        ratingImdb: 5.7,
        description:
            'Në një botë post-apokaliptike, gjashtë ushtarë në një mision të fshehtë duhet të transportojnë një paketë misterioze nëpër një arkipelag të ngrirë. ',
        photoSrc:
            'http://localhost:4000/images/movies/AAAABRpgAjiXoh3YCHvnc31BeBIIV-l3PFksMA7KkJpdGMG5UpOieHhdRKz5-itmm8LK_yEJaJbI7LdIrs9jB2k-AvD4K7mldJenJoRZ4RVY8OKBrwICoEkVCj96XhvlKA.jpg',
    },
    {
        title: 'The Extra Man (2010)',
        trailerSrc: 'https://www.youtube.com/embed/etxKmplTT9Q',
        duration: '108 min',
        releaseYear: 2010,
        ratingImdb: 5.8,
        description: 'Një burrë që shoqëron gra të pasura në Manhatan merr një djalë të ri në patronazh. ',
        photoSrc: 'http://localhost:4000/images/movies/7RhiXoCm6yEflHQvYtoLeAkDhaU.jpg',
    },
    {
        title: '14 Peaks: Nothing Is Impossible (2021)',
        trailerSrc: 'https://www.youtube.com/embed/8QH5hBOoz08',
        duration: '101 min',
        releaseYear: 2021,
        ratingImdb: 7.8,
        description:
            'Alpinisti i patrembur nepalez Nirmal Purxha, nis një kërkim në dukje të pamundur për të arritur të 14 majat 8 mijë metra të botës në 7 muaj. ',
        photoSrc:
            'http://localhost:4000/images/movies/AAAABdM8h2pl06NCiYL3_uSQ53x2O_kxCWz5cpJKX251-TFv35GWncYZjdbxfDmJwhda2SHLeIJCer_pCm90RxKgA1i4e2rLrHDNr94BhEFRa8QeeaxfEi80nsltpV95DQ.jpg',
    },
    {
        title: 'The Innocents (2021) a.k.a. De uskyldige',
        trailerSrc: 'https://www.youtube.com/embed/T8HR-zTRrCM',
        duration: '117 min',
        releaseYear: 2021,
        ratingImdb: 7,
        description:
            'Gjatë kohës së dritave polare një grup fëmijësh zbulojnë fuqitë e tyre të errëta dhe misterioze ndërkohë që të rriturit nuk i shohin, por kjo lojë merr një kthesë të rrezikshme. ',
        photoSrc: 'http://localhost:4000/images/movies/4hIptu4Yre7pIUhFa7GBZlfDTPW.jpg',
    },
    {
        title: 'Mean Dreams (2016)',
        trailerSrc: 'https://www.youtube.com/embed/jNOAVTX8PPE',
        duration: '108 minuta',
        releaseYear: 2016,
        ratingImdb: 6.1,
        description:
            "'Ëndrra të Këqija' : Një djalë 15-vjeçar vjedh një çantë me para droge dhe ia mbath me vajzën që dashuron. Ndërkohë që babai i saj polic, i dhunshëm dhe i korruptuar i ndjek, ata nisen në një udhëtim që do ju ndryshojë jetën përgjithmonë. ",
        photoSrc: 'http://localhost:4000/images/movies/AlowOYyprAAq85PPtE9LvoiYT1b.jpg',
    },
];

export const movieGenres = [
    { movieId: 344, genreId: 1 },
    { movieId: 344, genreId: 2 },
    { movieId: 345, genreId: 3 },
    { movieId: 345, genreId: 4 },
    { movieId: 345, genreId: 5 },
    { movieId: 346, genreId: 6 },
    { movieId: 346, genreId: 7 },
    { movieId: 347, genreId: 8 },
    { movieId: 347, genreId: 9 },
    { movieId: 347, genreId: 10 },
    { movieId: 348, genreId: 11 },
    { movieId: 348, genreId: 12 },
    { movieId: 348, genreId: 13 },
    { movieId: 349, genreId: 14 },
    { movieId: 349, genreId: 15 },
    { movieId: 349, genreId: 16 },
    { movieId: 350, genreId: 17 },
    { movieId: 350, genreId: 18 },
    { movieId: 350, genreId: 19 },
    { movieId: 351, genreId: 20 },
    { movieId: 351, genreId: 21 },
    { movieId: 352, genreId: 22 },
    { movieId: 352, genreId: 23 },
    { movieId: 352, genreId: 24 },
    { movieId: 353, genreId: 25 },
    { movieId: 353, genreId: 26 },
    { movieId: 353, genreId: 27 },
    { movieId: 354, genreId: 28 },
    { movieId: 354, genreId: 29 },
    { movieId: 355, genreId: 30 },
    { movieId: 355, genreId: 31 },
    { movieId: 356, genreId: 32 },
    { movieId: 356, genreId: 1 },
    { movieId: 357, genreId: 2 },
    { movieId: 357, genreId: 3 },
    { movieId: 358, genreId: 4 },
    { movieId: 358, genreId: 5 },
    { movieId: 358, genreId: 6 },
    { movieId: 359, genreId: 7 },
    { movieId: 359, genreId: 8 },
    { movieId: 360, genreId: 9 },
    { movieId: 360, genreId: 10 },
    { movieId: 360, genreId: 11 },
    { movieId: 361, genreId: 12 },
    { movieId: 361, genreId: 13 },
    { movieId: 361, genreId: 14 },
    { movieId: 362, genreId: 15 },
    { movieId: 362, genreId: 16 },
    { movieId: 362, genreId: 17 },
];

export const serieGenres = [
    { serieId: 1, genreId: 1 },
    { serieId: 1, genreId: 2 },
    { serieId: 1, genreId: 3 },
    { serieId: 2, genreId: 4 },
    { serieId: 2, genreId: 5 },
    { serieId: 3, genreId: 6 },
    { serieId: 3, genreId: 7 },
    { serieId: 5, genreId: 8 },
    { serieId: 4, genreId: 9 },
    { serieId: 6, genreId: 10 },
    { serieId: 6, genreId: 11 },
    { serieId: 6, genreId: 12 },
    { serieId: 6, genreId: 13 },
    { serieId: 7, genreId: 14 },
    { serieId: 7, genreId: 15 },
    { serieId: 7, genreId: 16 },
    { serieId: 7, genreId: 17 },
    { serieId: 8, genreId: 18 },
    { serieId: 10, genreId: 19 },
    { serieId: 9, genreId: 20 },
    { serieId: 11, genreId: 21 },
    { serieId: 12, genreId: 22 },
    { serieId: 13, genreId: 23 },
    { serieId: 14, genreId: 24 },
    { serieId: 15, genreId: 25 },
    { serieId: 16, genreId: 26 },
    { serieId: 17, genreId: 27 },
    { serieId: 18, genreId: 28 },
    { serieId: 19, genreId: 29 },
    { serieId: 19, genreId: 30 },
    { serieId: 19, genreId: 31 },
    { serieId: 19, genreId: 32 },
];

// export const movieGenres = [
//     [1, 2, 3],
//     [4, 5],
//     [6, 7, 8],
//     [9, 10],
//     [11, 12, 13],
//     [14, 15],
//     [16, 17],
//     [18, 19, 20],
//     [21, 22],
//     [23, 24],
//     [25, 26, 27],
//     [28, 29],
//     [30, 31, 32],
//     [1],
//     [2, 3],
//     [4],
//     [5, 6],
//     [7, 8],
//     [9, 10, 11],
//     [12],
//     [13, 14],
//     [15, 16, 17],
//     [18],
//     [19, 20, 21],
//     [22, 23],
//     [24],
//     [25, 26],
//     [27, 28, 29],
//     [30],
//     [31, 32, 1],
//     [2, 3, 4],
//     [5, 6, 7],
//     [8, 9],
//     [10, 11, 12],
//     [13, 14, 15],
//     [16],
//     [17, 18, 19],
//     [20, 21],
//     [22, 23, 24],
//     [25, 26],
//     [27, 28, 29],
//     [30, 31],
//     [32, 1],
//     [2, 3, 4],
//     [5, 6, 7, 8],
//     [9, 10, 11],
//     [12, 13, 14],
//     [15, 16],
//     [17, 18, 19],
//     [20, 21],
//     [22, 23, 24],
//     [25, 26],
//     [27, 28, 29],
//     [30, 31, 32],
// ];

// export const movieGenres = [
//     [1, 2, 3, 4],
//     [5, 3, 4, 6],
//     [1, 7, 8],
//     [1, 9, 6],
//     [1, 10, 6],
//     [11, 12, 3, 10],
//     [3, 10, 6],
//     [1, 9, 13, 14, 15],
//     [8, 12],
//     [1, 16, 10, 6],
//     [9, 5, 6],
//     [17, 9, 13],
//     [9, 12, 16],
//     [11, 9, 8, 18],
//     [1, 2, 9, 3],
//     [2, 9, 3],
//     [5, 19, 6],
//     [3, 20, 6],
//     [9, 21, 22],
//     [5],
//     [7, 12, 4],
//     [16, 6],
//     [9, 12],
//     [21, 8, 12],
//     [11, 8],
//     [9, 3, 6],
//     [9, 3, 6],
//     [23, 11, 12],
//     [9, 3, 6],
//     [9, 24, 25],
//     [9, 6],
//     [9],
//     [9, 12, 16],
//     [9, 19, 6],
//     [1, 2, 3, 6],
//     [1, 3, 6],
//     [6],
//     [12, 16],
//     [1, 6],
//     [9, 3, 16],
//     [17, 9, 20],
//     [9, 7, 5],
//     [9, 3, 10, 6],
//     [11, 9],
//     [26, 4],
//     [11, 9, 21],
//     [9, 8, 16],
//     [7, 6],
//     [9, 7, 16],
//     [9, 4, 27],
//     [1, 9, 3],
//     [12, 4],
//     [3, 19, 6],
//     [8, 12],
//     [9, 20],
//     [17, 9, 20],
//     [12, 16, 27],
//     [17, 13, 14, 15],
//     [28],
//     [11, 2, 13],
//     [12, 16],
//     [9, 16],
//     [2, 7, 6],
//     [9, 12, 4, 16],
//     [1, 9, 6],
//     [9, 13, 16],
//     [11, 7, 15, 6],
//     [11, 9, 13, 4],
//     [5, 6],
//     [3, 19, 10, 6],
//     [29, 12],
//     [1, 30, 3, 6],
//     [1, 17, 9, 14, 4],
//     [1, 23, 11, 2],
//     [30, 12],
//     [4, 16, 27],
//     [1, 12, 14],
//     [1, 2, 9, 14],
//     [9, 5],
//     [12, 4, 20],
//     [1, 3],
//     [17, 9, 3],
//     [9, 31, 3, 19],
//     [31, 12],
//     [1, 2, 9, 13, 14],
//     [1, 6],
//     [1, 11, 9],
//     [9, 3, 6],
//     [9, 7],
//     [1, 11, 7],
//     [1, 11, 7],
//     [5, 12, 6],
//     [2, 9, 19, 6],
//     [12, 16],
//     [5, 19, 6],
//     [1, 9, 3],
//     [1, 11, 9, 31],
//     [30, 5, 6],
//     [9, 16],
//     [5, 19, 6],
//     [1, 11, 12],
//     [9, 19, 6],
//     [11, 21],
//     [1, 9, 6],
//     [1, 9, 7],
//     [5, 12, 19],
//     [2, 9, 3],
//     [9, 3, 6],
//     [10, 6],
//     [1, 3, 6],
//     [1, 2, 6],
//     [1, 11, 8],
//     [17, 9],
//     [11, 21, 8],
//     [28],
//     [28],
//     [28],
//     [28],
//     [28],
//     [28],
//     [28],
//     [28],
//     [28],
//     [28],
//     [28],
//     [28],
//     [23, 11, 12],
//     [28],
//     [1, 29, 6],
//     [9, 13, 15],
//     [9, 12, 3],
//     [2, 9, 12, 3],
//     [1, 11, 17],
//     [9, 12],
//     [9, 24, 6],
//     [1, 2, 12],
//     [1, 11, 12],
//     [8, 5, 19],
//     [12, 4, 16],
//     [11, 12, 3],
//     [1, 14],
//     [1, 11, 9],
//     [1, 2, 9, 5],
//     [9, 5],
//     [9, 24],
//     [1, 9, 25, 6],
//     [1, 9, 20],
//     [1, 9, 3],
//     [11, 8],
//     [9, 5, 6],
//     [1, 11, 2, 4],
//     [9, 5, 6],
//     [12, 22, 16],
//     [9, 12],
//     [9, 12],
//     [1, 11, 12, 4],
//     [1, 9, 6],
//     [1, 9, 3],
//     [1, 11],
//     [1, 23, 11],
//     [9, 31, 3, 6],
//     [12, 16],
//     [9, 12],
//     [9, 5],
//     [9, 16],
//     [23, 11, 12],
//     [1, 20],
//     [11, 21],
//     [9, 18, 3],
//     [1, 6],
//     [1, 11, 8],
//     [9, 4],
//     [12, 4, 27],
//     [9, 19, 6],
//     [12],
//     [17, 9, 4],
//     [11, 9, 13],
//     [11, 5, 12],
//     [5, 6],
//     [1, 5],
//     [9, 31, 3, 16],
//     [1, 9, 6],
//     [1, 26, 12],
//     [1, 9, 30, 12],
//     [11, 24],
//     [9, 13, 14, 25],
//     [5, 19, 6],
//     [8, 5, 19],
//     [9],
//     [23, 2, 4],
//     [12, 4, 16, 10],
//     [9, 12, 3],
//     [17, 9, 21, 4],
//     [9, 6],
//     [9],
//     [1, 4, 16],
//     [9, 19],
//     [9, 13, 3, 4, 25],
//     [9, 21, 12],
//     [5, 19, 6],
//     [9, 14],
//     [9, 3, 19, 4],
//     [9, 3, 19],
//     [11, 21, 12],
//     [1, 2, 12],
//     [1, 12, 3],
//     [11, 21],
//     [9, 5, 19],
//     [1, 9, 20],
//     [1, 11, 6],
//     [1, 11, 12],
//     [5],
//     [1, 19, 6],
//     [9, 7, 6],
//     [9, 3, 6],
//     [9, 21, 22],
//     [1, 11, 4, 25],
//     [9, 3, 6],
//     [1, 11, 7],
//     [1, 2, 3, 6],
//     [1, 2, 9, 14],
//     [1, 9, 13, 15],
//     [1, 2, 3, 6],
//     [9],
//     [12],
//     [12],
//     [12, 3],
//     [12],
//     [31, 3, 19, 6],
//     [1, 18, 3, 19],
//     [9, 4, 16, 27],
//     [11, 21, 30, 12],
//     [1, 9, 6],
//     [12],
//     [9, 25, 6],
//     [9, 19, 6],
//     [9, 3, 4, 6],
//     [23, 21, 12],
//     [1, 9, 6],
//     [8, 12, 16],
//     [12, 4, 16],
//     [1, 3, 20],
//     [1, 11, 8],
//     [1, 14, 15],
//     [5, 6],
//     [9, 7],
//     [1, 9, 7],
//     [11, 26, 4, 20],
//     [1, 12, 3],
//     [1, 11, 7],
//     [9],
//     [1, 7, 19],
//     [12, 3],
//     [1, 2, 9, 14],
//     [9, 5, 19, 4],
//     [9, 5, 19],
//     [9, 12, 16],
//     [26, 3, 4],
//     [1, 7],
//     [17, 9, 22],
//     [9, 12],
//     [18, 12],
//     [1, 12, 3],
//     [9, 5, 19, 25],
//     [1, 5, 6],
//     [6],
//     [1, 2, 3],
//     [1, 9, 3],
//     [1, 9, 13, 14],
//     [21, 12, 4, 27],
//     [9, 3],
//     [1, 11, 9],
//     [17, 9, 13],
//     [9, 19, 16],
//     [9, 27],
//     [9, 16, 27],
//     [23, 21, 12],
//     [8, 5, 6],
//     [1, 12, 3],
//     [12],
//     [1, 11, 9],
//     [9, 16],
//     [9, 19, 6],
//     [5, 6],
//     [1, 11, 5],
//     [1, 11, 4, 10],
//     [1, 3, 10, 6],
//     [1, 9, 3],
//     [9, 3],
//     [28],
//     [1, 12, 3],
//     [9],
//     [1, 2, 9, 3],
//     [17, 9],
//     [1, 11, 7],
//     [1, 30, 12],
//     [1, 9, 13],
//     [9, 5, 19],
//     [1, 3, 6],
//     [18, 12],
//     [2, 9],
//     [1, 3, 6],
//     [1, 9, 7],
//     [17, 9, 31],
//     [9],
//     [1, 2, 9, 8],
// ];

export const genres = [
    { name: 'Aksion' },
    { name: 'Aziatik' },
    { name: 'Krim' },
    { name: 'NETFLIX' },
    { name: 'Horror' },
    { name: 'Thriller' },
    { name: 'Fantashkencë' },
    { name: 'Fantazi' },
    { name: 'Dramë' },
    { name: 'Spanjoll' },
    { name: 'Aventurë' },
    { name: 'Komedi' },
    { name: 'Histori' },
    { name: 'Luftë' },
    { name: 'Rus' },
    { name: 'Romancë' },
    { name: 'Biografi' },
    { name: 'Italian' },
    { name: 'Mister' },
    { name: 'Sport' },
    { name: 'Familjar' },
    { name: 'Muzikë' },
    { name: 'Animuar' },
    { name: 'Erotik +18' },
    { name: 'Nordik' },
    { name: 'Dokumentar' },
    { name: 'Turk' },
    { name: 'SË SHPEJTI' },
    { name: 'Gjerman' },
    { name: 'Francez' },
    { name: 'Hindi' },
];

export const series = [
    {
        id: 1,
        title: 'Rebelde',
        trailerSrc: 'https://www.youtube.com/watch?v=BJYJksHREIc',
        description:
            'Rebelde ndjek jetën e studentëve në Elite Way School, një shkollë të prestigjshme private në qytetin e Meksikos.',
        releaseYear: 2022,
        ratingImdb: 6.3,
        photoSrc: 'http://localhost:4000/images/series/rebelde.jpg',
    },
    {
        id: 2,
        title: 'Snowfall',
        trailerSrc: 'https://www.youtube.com/embed/BJYJksHREIc',
        description:
            'Snowfall është një serial televiziv amerikan i krijuar nga John Singleton, Eric Amadio dhe Dave Andron. Seria është vendosur në fillim të viteve 1980, në Los Angeles, dhe shikon fillimin e luftës së kokainës së ndërthurur dhe rritjen e epidemisë së AIDS.',
        releaseYear: 2017,
        ratingImdb: 8.2,
        photoSrc: 'http://localhost:4000/images/series/snowfall.jpg',
    },
    {
        id: 3,
        title: 'Man vs Bee',
        trailerSrc: 'https://www.youtube.com/embed/BJYJksHREIc',
        description:
            'Man vs Bee është një serial dokumentar që shqyrton përballjen midis bimëve dhe bletëve në botën tonë.',
        releaseYear: 2022,
        ratingImdb: 6.8,
        photoSrc: 'http://localhost:4000/images/series/manbee.jpg',
    },
    {
        id: 4,
        title: 'Moonknight',
        trailerSrc: 'https://www.youtube.com/embed/x7Krla_UxRg',
        description: 'Moonknight ndjek aventurat e Marc Spector, një ushtarak që merr fuqi nga një qenje mitologjike.',
        releaseYear: 2022,
        ratingImdb: 7.4,
        photoSrc: 'http://localhost:4000/images/series/moonknight.jpg',
    },
    {
        id: 5,
        title: 'Peacemaker',
        trailerSrc: 'https://www.youtube.com/embed/WHXq62VCaCM',
        description:
            'Peacemaker është një serial televiziv amerikan i krijuar nga James Gunn për shërbimin e strukturuar DC dhe HBO Max.',
        releaseYear: 2022,
        ratingImdb: 8.3,
        photoSrc: 'http://localhost:4000/images/series/peacemaker.jpg',
    },
    {
        id: 6,
        title: 'Top Boy',
        trailerSrc: 'https://www.youtube.com/embed/BYLYZ7OsymE',
        description:
            'Top Boy është një serial televiziv britanik i krijimit të Ronan Bennet. Seriali ndjek jetën e adoleshentëve dhe atyre që ndihmojnë në trafikun e drogës në një lagje të varfër në Londër.',
        releaseYear: 2011,
        ratingImdb: 8.4,
        photoSrc: 'http://localhost:4000/images/series/topboy.jpg',
    },
    {
        id: 7,
        title: 'Ganglands',
        trailerSrc: 'https://www.youtube.com/embed/0VZ2Nbx8gHI',
        description:
            'Ganglands është një serial kriminal francez i bazuar në historinë e vërtetë të një familjeje të cila drejton një bandë të organizuar kriminale në Pariz.',
        releaseYear: 2021,
        ratingImdb: 7.0,
        photoSrc: 'http://localhost:4000/images/series/ganglands.jpg',
    },
    {
        id: 8,
        title: 'Ozark',
        trailerSrc: 'https://www.youtube.com/embed/5hAXVqrljbs',
        description:
            'Ozark është një serial dramatik amerikan që ndjek jetën e një familjeje që zhvillon një biznes të madh të pastrimit të parave në Ozark Mountains në Missouri.',
        releaseYear: 2017,
        ratingImdb: 8.5,
        photoSrc: 'http://localhost:4000/images/series/ozark.jpg',
    },
    {
        id: 9,
        title: 'Resident Alien',
        trailerSrc: 'https://www.youtube.com/embed/T4J7QjGNTs4',
        description:
            'Resident Alien është një serial humoristik shkencor-fantastik amerikan që ndjek një ekstraterrestrial që përpiqet të shpëtojë nga identiteti i tij të fshehtë duke jetuar si një mjek në një qytet provincial amerikan.',
        releaseYear: 2021,
        ratingImdb: 8.1,
        photoSrc: 'http://localhost:4000/images/series/alien.jpg',
    },
    {
        id: 10,
        title: 'Bridgerton',
        trailerSrc: 'https://www.youtube.com/embed/U4JYAx5rNRA',
        description:
            'Bridgerton është një serial historik-dramatik britaniko-amerikan i krijuar nga Chris Van Dusen dhe prodhuar nga Shonda Rhimes. Seriali ndjek jetën e familjes Bridgerton në Londër në vitet 1813-1827.',
        releaseYear: 2020,
        ratingImdb: 7.3,
        photoSrc: 'http://localhost:4000/images/series/bridgerton.jpg',
    },
    {
        id: 11,
        title: 'Superman & Lois',
        trailerSrc: 'https://www.youtube.com/embed/SJPJPUpNvDw',
        description:
            'Superman & Lois është një serial superheroi amerikan i bazuar në personazhet Superman dhe Lois Lane të DC Comics. Seriali ndjek jetën e Superman dhe Lois Lane pas martesës së tyre, duke u përballur me sfida të jetës personale dhe të profesionit të tyre si superheronj.',
        releaseYear: 2021,
        ratingImdb: 7.8,
        photoSrc: 'http://localhost:4000/images/series/superman.jpg',
    },
    {
        id: 12,
        title: 'Attack on Titan',
        trailerSrc: 'https://www.youtube.com/embed/MGRm4IzK1SQ',
        description:
            'Attack on Titan është një serial anime japonez i bazuar në manga me të njëjtin emër të shkruar nga Hajime Isayama. Seria ndjek historinë e një bote ku qytetërimi njerëzor është shkatërruar nga krijesa gigante të njohura si Titanë.',
        releaseYear: 2013,
        ratingImdb: 9.0,
        photoSrc: 'http://localhost:4000/images/series/aot.png',
    },
    {
        id: 13,
        title: 'Kengan Ashura',
        trailerSrc: 'https://www.youtube.com/embed/CNuY4ymi4Fs',
        description:
            'Kengan Ashura është një serial anime japonez i bazuar në mangan me të njëjtin emër të shkruar nga Yabako Sandrovich. Seria ndjek historinë e Tokitës Ouma, një luftëtar të ri që përfshihet në një turne luftarak të quajtur Kengan për të zotëruar një ndërhyrje në biznesin e tij të firmave.',
        releaseYear: 2019,
        ratingImdb: 8.0,
        photoSrc: 'http://localhost:4000/images/series/baki.png',
    },
    {
        id: 14,
        title: 'Elite',
        trailerSrc: 'https://www.youtube.com/embed/QNwhAdrdwp0',
        description:
            'Elite është një serial spanjoll i krijuar nga Carlos Montero dhe Darío Madrona. Seriali ndjek jetën e studentëve të një shkolle të lartë private në Spanjë, ku ndodhin ngjarje tragjike dhe sekrete të ndryshme dalin në dritë.',
        releaseYear: 2018,
        ratingImdb: 7.4,
        photoSrc: 'http://localhost:4000/images/series/elite.png',
    },
    {
        id: 15,
        title: 'The Flash',
        trailerSrc: 'https://www.youtube.com/embed/hebWYacbdvc',
        description:
            'The Flash është një serial superheroi amerikan i krijuar nga Greg Berlanti, Andrew Kreisberg dhe Geoff Johns, bazuar në personazhin e DC Comics me të njëjtin emër. Seria ndjek aventurat e Barry Allen, një shkencëtar forenzik që fiton aftësinë për të ecën me shpejtësi të mahnitshme pas një aksidenti laboratori.',
        releaseYear: 2014,
        ratingImdb: 7.6,
        photoSrc: 'http://localhost:4000/images/series/flash.png',
    },
    {
        id: 16,
        title: 'Power Book IV: Force',
        trailerSrc: 'https://www.youtube.com/embed/uiGzLrJSk8E',
        description:
            'Power Book IV: Force është një serial dramatik amerikan i krijuar nga Courtney A. Kemp për Starz. Seria ndjek jetën e Tommy Egan, një personazh që u paraqit për herë të parë në serialin "Power", ndërsa ai përfshihet në botën e krimit të organizuar në qytetin e Çikagos.',
        releaseYear: 2022,
        ratingImdb: 8.1,
        photoSrc: 'http://localhost:4000/images/series/force.png',
    },
    {
        id: 17,
        title: 'Halo',
        trailerSrc: 'https://www.youtube.com/embed/5KZ3MKraNKY',
        description:
            'Halo është një serial televiziv amerikan i zhanrit science fiction i krijuar nga Kyle Killen dhe Steven Kane. Bazuar në lojën e njohur video "Halo" të Microsoft Studios, seria ndjek aventurat e Master Chief, një super-soldat i quajtur për të mbrojtur një botë të ashpër nga kërcënimi i një alliance të jashtme të njohur si Covenant.',
        releaseYear: 2022,
        ratingImdb: 7.0,
        photoSrc: 'http://localhost:4000/images/series/halo.png',
    },
    {
        id: 18,
        title: 'The Last Kingdom',
        trailerSrc: 'https://www.youtube.com/embed/BJYJksHREIc',
        description:
            'The Last Kingdom është një serial historik britanik i krijuar nga Stephen Butchard. Bazuar në serinë e librave "Saxon Stories" të Bernard Cornwell, seria ndjek aventurat e Uhtred Ragnarson, një djalë saks i cili përpiqet të mbrojë dhe të rikthejë territorin e tij në Britaninë e Mesme në periudhën e shekullit të IX.',
        releaseYear: 2015,
        ratingImdb: 8.5,
        photoSrc: 'https://www.youtube.com/watch?Ht6U6AifKmE',
    },
    {
        id: 19,
        title: 'Knightfall',
        trailerSrc: 'https://www.youtube.com/embed/F9dtepkeR0I',
        description:
            'Knightfall është një serial dramatik-historik amerikan i krijuar nga Don Handfield dhe Richard Rayner për History Channel. Seria ndjek rrugën e lëvizjes së Ku Klux Klan, duke filluar nga themelimi i saj në vitet e pasluftës në Selma, Alabama, në vitin 1865, deri në kohën e bllokimit të saj në vitin 1871.',
        releaseYear: 2017,
        ratingImdb: 6.7,
        photoSrc: 'http://localhost:4000/images/series/knightfall.png',
    },
];

export const episodes = [
    {
        id: 1,
        title: 'Snowfall Sezoni 1 Episodi 1',
        description:
            "Sipërmarrësi i rrugës nga qendra jugore Franklin Saint bën një hap në lojën e kokainës. Oficeri i pakënaqur i CIA-s, Teddy McDonald, bën aleancë me një ushtar Contra. Mundësi Luchador, Gustavo El Oso Zapata hyn në një familje karteli meksikan.'.",
        photoSrc: 'http://localhost:4000/images/rsz_fistful_of_vengeance.png',
        videoSrc: '//vidmoly.net/embed-09lyu1ioabwf.html',
        seasonId: 1,
    },
    {
        id: 2,
        title: 'Snowfall Sezoni 1 Episodi 2',
        description:
            'Franklin vazhdon punën e tij korrier për Avi-n. Takimi i parë i Tedit me Avin nuk pritet. Gustavo mëson se nga kush vodhi - dhe përfundoi duke u vrarë në një pushtim në shtëpi..',
        photoSrc: 'http://localhost:4000/images/series/snowfall.jpg',
        videoSrc: '//vidmoly.net/embed-09lyu1ioabwf.html',
        seasonId: 1,
    },
    {
        id: 3,
        title: 'Origin Sezoni 1 Episodi 1',
        description:
            "Kai Jin, një kuzhinier i ri në San Francisko, ngatërrohet me ndjekjen e Triadës Kineze për fuqitë e lashta vdekjeprurëse të njohura si 'Wu Xing'.",
        photoSrc: 'http://localhost:4000/images/rsz_fistful_of_vengeance.png',
        videoSrc: '//vidmoly.net/embed-09lyu1ioabwf.html',
        seasonId: 1,
    },
];

export const seasons = [
    {
        id: 1,
        title: 'Rebelde - Season 1',
        photoSrc: 'http://localhost:4000/images/series/rebelde.jpg',
        releaseYear: 2022,
        ratingImdb: 6.5,
        serieId: 1,
    },
    {
        id: 2,
        title: 'Snowfall - Season 1',
        photoSrc: 'http://localhost:4000/images/series/snowfall.jpg',
        releaseYear: 2017,
        ratingImdb: 8.0,
        serieId: 2,
    },
    {
        id: 3,
        title: 'Man vs Bee - Season 1',
        photoSrc: 'http://localhost:4000/images/series/manbee.jpg',
        releaseYear: 2022,
        ratingImdb: 7.5,
        serieId: 3,
    },
    {
        id: 4,
        title: 'Moonknight - Season 1',
        photoSrc: 'http://localhost:4000/images/series/moonknight.jpg',
        releaseYear: 2022,
        ratingImdb: 9.0,
        serieId: 4,
    },
    {
        id: 5,
        title: 'Peacemaker - Season 1',
        photoSrc: 'http://localhost:4000/images/series/peacemaker.jpg',
        releaseYear: 2022,
        ratingImdb: 7.5,
        serieId: 5,
    },
    {
        id: 6,
        title: 'Snowfall - Season 2',
        photoSrc: 'http://localhost:4000/images/series/snowfall.jpg',
        releaseYear: 2021,
        ratingImdb: 7.8,
        serieId: 2,
    },
    {
        id: 7,
        title: 'Moonknight - Season 2',
        photoSrc: 'http://localhost:4000/images/series/moonknight.jpg',
        releaseYear: 2021,
        ratingImdb: 8.2,
        serieId: 4,
    },
];
