// #region "Data used for seeding the database"
export const users = [
    {
        id: 1,
        userName: "admin",
        email: "admin@yahoo.com",
        password: "Admin22%",
        role: "Admin",
        bio: "Admin bio test",
        active: true,
    },
    {
        id: 2,
        userName: "test1",
        email: "test1@email.com",
        password: "Test22%",
        role: "User",
        bio: "Test 1 bio test",
        active: true,
    },
    {
        id: 3,
        userName: "test2",
        email: "test2@email.com",
        password: "Test22%",
        role: "User",
        bio: "Test 2 bio test",
        active: true,
    },
];

export const genres = [
    { id: 1, name: "Action" },
    { id: 2, name: "Asian" },
    { id: 3, name: "Crime" },
    { id: 4, name: "Netflix" },
    { id: 5, name: "Horror" },
    { id: 6, name: "Thriller" },
    { id: 7, name: "Fantasy" },
    { id: 8, name: "Sci-Fi" },
    { id: 9, name: "Drama" },
    { id: 10, name: "Spanish" },
    { id: 11, name: "Adventure" },
    { id: 12, name: "Comedy" },
    { id: 13, name: "History" },
    { id: 14, name: "War" },
    { id: 15, name: "Russian" },
    { id: 16, name: "Romance" },
    { id: 17, name: "Biography" },
    { id: 18, name: "Italian" },
    { id: 19, name: "Mystery" },
    { id: 20, name: "Sport" },
    { id: 21, name: "Family" },
    { id: 22, name: "Music" },
    { id: 23, name: "Animation" },
    { id: 24, name: "Erotic +18" },
    { id: 25, name: "Nordic" },
    { id: 26, name: "Documentary" },
    { id: 27, name: "Turkish" },
    { id: 28, name: "COMING SOON" },
    { id: 29, name: "German" },
    { id: 30, name: "French" },
    { id: 31, name: "Hindi" },
];

export const actors = [
    {
        id: 1,
        fullname: "Tom Holland",
        description: "A brief description for Tom Holland.",
        debut: "2012",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 2,
        fullname: "Zendaya",
        description: "A brief description for Zendaya.",
        debut: "2010",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 3,
        fullname: "Benedict Cumberbatch",
        description: "A brief description for Benedict Cumberbatch.",
        debut: "2000",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 4,
        fullname: "Mackenzie Davis",
        description: "A brief description for Mackenzie Davis.",
        debut: "2012",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 5,
        fullname: "Finn Wolfhard",
        description: "A brief description for Finn Wolfhard.",
        debut: "2014",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 6,
        fullname: "Brooklynn Prince",
        description: "A brief description for Brooklynn Prince.",
        debut: "2015",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 7,
        fullname: "Leighton Meester",
        description: "A brief description for Leighton Meester.",
        debut: "1999",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 8,
        fullname: "Christina Wolfe",
        description: "A brief description for Christina Wolfe.",
        debut: "2013",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 9,
        fullname: "Damson Idris",
        description: "A brief description for Damson Idris.",
        debut: "2010",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 10,
        fullname: "Carter Hudson",
        description: "A brief description for Carter Hudson.",
        debut: "2007",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 11,
        fullname: "Giorgio Cantarini",
        description: "A brief description for Giorgio Cantarini.",
        debut: "1999",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 12,
        fullname: "Aurora Quattrocchi",
        description: "A brief description for Aurora Quattrocchi.",
        debut: "2005",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 13,
        fullname: "Franz Rogowski",
        description: "A brief description for Franz Rogowski.",
        debut: "2009",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 14,
        fullname: "Gokhan Yikilkan",
        description: "A brief description for Gokhan Yikilkan.",
        debut: "2011",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 15,
        fullname: "Belçim Bilgin",
        description: "A brief description for Belçim Bilgin.",
        debut: "2006",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 16,
        fullname: "Bariş Arduc",
        description: "A brief description for Bariş Arduc.",
        debut: "2010",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 17,
        fullname: "Mario Casas",
        description: "A brief description for Mario Casas.",
        debut: "2006",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 18,
        fullname: "Ana Wagener",
        description: "A brief description for Ana Wagener.",
        debut: "2001",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 19,
        fullname: "José Coronado",
        description: "A brief description for José Coronado.",
        debut: "1996",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 20,
        fullname: "Michael Jai White",
        description: "A brief description for Michael Jai White.",
        debut: "1992",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 21,
        fullname: "Julian Sands",
        description: "A brief description for Julian Sands.",
        debut: "1984",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 22,
        fullname: "Eamonn Walker",
        description: "A brief description for Eamonn Walker.",
        debut: "1994",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 23,
        fullname: "Jacob Tremblay",
        description: "A brief description for Jacob Tremblay.",
        debut: "2013",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 24,
        fullname: "Julia Roberts",
        description: "A brief description for Julia Roberts.",
        debut: "1987",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 25,
        fullname: "Owen Wilson",
        description: "A brief description for Owen Wilson.",
        debut: "1996",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 26,
        fullname: "Gemma Chan",
        description: "A brief description for Gemma Chan.",
        debut: "2006",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 27,
        fullname: "Richard Madden",
        description: "A brief description for Richard Madden.",
        debut: "2007",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 28,
        fullname: "Kumail Nanjiani",
        description: "A brief description for Kumail Nanjiani.",
        debut: "2008",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 29,
        fullname: "Asim Chaudhry",
        description: "A brief description for Asim Chaudhry.",
        debut: "2011",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 30,
        fullname: "Kobna Holdbrook-Smith",
        description: "A brief description for Kobna Holdbrook-Smith.",
        debut: "2008",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 31,
        fullname: "Giovanna Mezzogiorno",
        description: "A brief description for Giovanna Mezzogiorno.",
        debut: "1997",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 32,
        fullname: "Stefano Accorsi",
        description: "A brief description for Stefano Accorsi.",
        debut: "1996",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 33,
        fullname: "Amanda Collin",
        description: "A brief description for Amanda Collin.",
        debut: "2010",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 34,
        fullname: "Dar Salim",
        description: "A brief description for Dar Salim.",
        debut: "2009",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 35,
        fullname: "Noomi Rapace",
        description: "A brief description for Noomi Rapace.",
        debut: "2000",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 36,
        fullname: "Joel Kinnaman",
        description: "A brief description for Joel Kinnaman.",
        debut: "2003",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 37,
        fullname: "Kevin Hart",
        description: "A brief description for Kevin Hart.",
        debut: "2001",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 38,
        fullname: "John Cena",
        description: "A brief description for John Cena.",
        debut: "2000",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 39,
        fullname: "Danielle Brooks",
        description: "A brief description for Danielle Brooks.",
        debut: "2011",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 40,
        fullname: "Ashley Walters",
        description: "A brief description for Ashley Walters.",
        debut: "2000",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 41,
        fullname: "Kane Robinson",
        description: "A brief description for Kane Robinson.",
        debut: "2005",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 42,
        fullname: "Micheal Ward",
        description: "A brief description for Micheal Ward.",
        debut: "2014",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 43,
        fullname: "Samy Seghir",
        description: "A brief description for Samy Seghir.",
        debut: "2011",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 44,
        fullname: "Manon Azem",
        description: "A brief description for Manon Azem.",
        debut: "2009",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 45,
        fullname: "Tracy Gotoas",
        description: "A brief description for Tracy Gotoas.",
        debut: "2003",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 46,
        fullname: "Jason Bateman",
        description: "A brief description for Jason Bateman.",
        debut: "1987",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 47,
        fullname: "Laura Linney",
        description: "A brief description for Laura Linney.",
        debut: "1993",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 48,
        fullname: "Sofia Hublitz",
        description: "A brief description for Sofia Hublitz.",
        debut: "2013",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 49,
        fullname: "Alan Tudyk",
        description: "A brief description for Alan Tudyk.",
        debut: "2000",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
    {
        id: 50,
        fullname: "Sara Tomko",
        description: "A brief description for Sara Tomko.",
        debut: "2011",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
    },
];

export const movies = [
    {
        id: 1,
        title: "Freaks Out",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 141,
        dateAired: "10/28/2021",
        ratingImdb: 7.4,
        description:
            "Matilde, Cencio, Fulvio, and Mario are united when World War II strikes Rome. Israel, their circus owner, disappears in an attempt to find a place abroad for all of them.",
        photoSrc: "http://localhost:4000/images/movies/1TkkTo8UiRl5lWM5qkAISHXg0fU.jpg",
        photoSrcProd:
            "https://movielandia-avenger22s-projects.vercel.app/images/movies/1TkkTo8UiRl5lWM5qkAISHXg0fU.jpg",
    },
    {
        id: 2,
        title: "My Father's Violin",
        trailerSrc: "https://www.youtube.com/embed/GAmo87Ep-tI",
        duration: 112,
        dateAired: "11/17/2022",
        ratingImdb: 6.5,
        description:
            "Through their shared grief and connection to music, an orphaned girl bonds with her emotionally distant, successful violinist uncle.",
        photoSrc: "http://localhost:4000/images/movies/fathersviolin.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/movies/fathersviolin.jpg",
    },
    {
        id: 3,
        title: "The Invisible Guest",
        trailerSrc: "https://www.youtube.com/embed/epCg2RbyF80",
        duration: 126,
        dateAired: "03/24/2017",
        ratingImdb: 8.1,
        description:
            "A young businessman faces a lawyer in an attempt to prove his innocence for the murder of his girlfriend.",
        photoSrc: "http://localhost:4000/images/movies/8c9fce3c0ffa46576423d44b525447edc25f1396.jpg",
        photoSrcProd:
            "https://movielandia-avenger22s-projects.vercel.app/images/movies/8c9fce3c0ffa46576423d44b525447edc25f1396.jpg",
    },
    {
        id: 4,
        title: "Blood and Bone",
        trailerSrc: "https://www.youtube.com/embed/KyOtQr5u-uY",
        duration: 93,
        dateAired: "01/17/2009",
        ratingImdb: 6.7,
        description:
            "Ex-con Boun is the new force on the underground street fighting scene in Los Angeles. When he defeats the reigning champion, the local gangster boss wants to enlist Boun in a series of high-stakes international matches. Boun's refusal sets off an explosive showdown between two powerful enemies risking everything.",
        photoSrc: "http://localhost:4000/images/movies/5254_1_ladsfgfdgdfgdfgfdgfdgrge.jpg",
        photoSrcProd:
            "https://movielandia-avenger22s-projects.vercel.app/images/movies/5254_1_ladsfgfdgdfgdfgfdgfdgrge.jpg",
    },
    {
        id: 5,
        title: "Spider-Man: No Way Home",
        trailerSrc: "https://www.youtube.com/embed/JfVOs4VSpmA",
        duration: 148,
        dateAired: "12/17/2021",
        ratingImdb: 8.7,
        description:
            "Peter Parker is unmasked and no longer able to separate his normal life from the high stakes of being a Super Hero. When he seeks help from Doctor Strange, the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
        photoSrc: "http://localhost:4000/images/movies/1gxZrx9gL9ov2c1NpXimEUzMTmh.jpg",
        photoSrcProd:
            "https://movielandia-avenger22s-projects.vercel.app/images/movies/1gxZrx9gL9ov2c1NpXimEUzMTmh.jpg",
    },
    {
        id: 6,
        title: "Iron Will",
        trailerSrc: "https://www.youtube.com/embed/giLeHfkJeXU",
        duration: 108,
        dateAired: "01/17/1994",
        ratingImdb: 6.6,
        description:
            "After his father's death, the responsibility to care for the family falls on Will's shoulders. He enters a dog race that requires long hours of racing and a steely will to win.",
        photoSrc: "http://localhost:4000/images/movies/6Ujbtp0NklUoQ67s32HyW6R5540.jpg",
        photoSrcProd:
            "https://movielandia-avenger22s-projects.vercel.app/images/movies/6Ujbtp0NklUoQ67s32HyW6R5540.jpg",
    },
    {
        id: 7,
        title: "Panama",
        trailerSrc: "https://www.youtube.com/embed/2GSzkfe1aAY",
        duration: 94,
        dateAired: "11/18/2022",
        ratingImdb: 0,
        description:
            "A former marine is hired by a defense contractor to travel to Panama to complete an arms deal. During the process, he becomes involved in the U.S. invasion of Panama and learns an important lesson about the true nature of political power.",
        photoSrc: "http://localhost:4000/images/movies/82I3tDsGDTMy7lHar84Gz0jUuyW.jpg",
        photoSrcProd:
            "https://movielandia-avenger22s-projects.vercel.app/images/movies/82I3tDsGDTMy7lHar84Gz0jUuyW.jpg",
    },
    {
        id: 8,
        title: "Eternals",
        trailerSrc: "https://www.youtube.com/embed/x_me3xsvDgk",
        duration: 156,
        dateAired: "11/05/2021",
        ratingImdb: 6.8,
        description:
            "The Eternals are a team of ancient aliens who have been living on Earth in secret for thousands of years. When an unexpected tragedy forces them out of the shadows, they must reunite against mankind's oldest enemy.",
        photoSrc: "http://localhost:4000/images/movies/1RjyfPLsZTq3lUdJY7pTzcmpPKl.jpg",
        photoSrcProd:
            "https://movielandia-avenger22s-projects.vercel.app/images/movies/1RjyfPLsZTq3lUdJY7pTzcmpPKl.jpg",
    },
    {
        id: 9,
        title: "Money Trap",
        trailerSrc: "https://www.youtube.com/embed/gcH0KPQVVH4",
        duration: 121,
        dateAired: "12/29/2022",
        ratingImdb: 6,
        description:
            "Asim Noyan deceives people with his lies and games. Asim Noyan and his gang, whom no one else has been able to capture, get involved in another scam.",
        photoSrc: "http://localhost:4000/images/movies/4kiVg3QJQghjtRupyfWYI3T1R0O-1.jpg",
        photoSrcProd:
            "https://movielandia-avenger22s-projects.vercel.app/images/movies/4kiVg3QJQghjtRupyfWYI3T1R0O-1.jpg",
    },
    {
        id: 10,
        title: "Inch'Allah",
        trailerSrc: "https://www.youtube.com/embed/53XLPquQD6Q",
        duration: 102,
        dateAired: "09/09/2012",
        ratingImdb: 6.8,
        description:
            "A Canadian doctor finds her sympathies severely tested while working in the conflict-ravaged Palestinian territories.",
        photoSrc: "http://localhost:4000/images/movies/9BCd5LdVHQmWqEnDTJ5Ut8idstP-1.jpg",
        photoSrcProd:
            "https://movielandia-avenger22s-projects.vercel.app/images/movies/9BCd5LdVHQmWqEnDTJ5Ut8idstP-1.jpg",
    },
    {
        id: 11,
        title: "Mobile Suit Gundam: Hathaway",
        trailerSrc: "https://www.youtube.com/embed/MzxnPP5TLeU",
        duration: 95,
        dateAired: "06/11/2021",
        ratingImdb: 6.6,
        description:
            "Hathaway Noa becomes part of a terrorist organization called Mufti that organizes an attack on Earth Federation ministers.",
        photoSrc: "http://localhost:4000/images/movies/6gw8onh4FKsruBA7Oouv01EFxzn-1.jpg",
        photoSrcProd:
            "https://movielandia-avenger22s-projects.vercel.app/images/movies/6gw8onh4FKsruBA7Oouv01EFxzn-1.jpg",
    },
    {
        id: 12,
        title: "Rescued by Ruby",
        trailerSrc: "https://www.youtube.com/embed/-Pwxr307O4w",
        duration: 90,
        dateAired: "03/17/2022",
        ratingImdb: 7.3,
        description:
            "Pursuing his dream to join an elite K-9 unit, a state trooper partners with a smart but unruly shelter dog named Ruby.",
        photoSrc: "http://localhost:4000/images/movies/ruby.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/movies/ruby.jpg",
    },
    {
        id: 13,
        title: "The Girl on the Mountain",
        trailerSrc: "https://www.youtube.com/embed/Y0vh8jQ7HMQ",
        duration: 94,
        dateAired: "08/21/2021",
        ratingImdb: 6.4,
        description:
            "When an isolated forester finds a mute little girl wandering alone in the woods, he must protect her from the evil forces determined to end her life.",
        photoSrc: "http://localhost:4000/images/movies/1ZiZ3eVUWPxJROTkYbH8FBC9UuB.jpg",
        photoSrcProd:
            "https://movielandia-avenger22s-projects.vercel.app/images/movies/1ZiZ3eVUWPxJROTkYbH8FBC9UuB.jpg",
    },
    {
        id: 14,
        title: "The Weekend Away",
        trailerSrc: "https://www.youtube.com/embed/XpfjN-7Hf-8",
        duration: 89,
        dateAired: "03/03/2022",
        ratingImdb: 5.6,
        description:
            "A weekend getaway to Croatia goes awry when a woman is accused of murdering her best friend. As she attempts to clear her name and uncover the truth, her efforts reveal a painful secret.",
        photoSrc: "http://localhost:4000/images/movies/6MS0QEl7UK2gdFFbHfNwuYlsq4H.jpg",
        photoSrcProd:
            "https://movielandia-avenger22s-projects.vercel.app/images/movies/6MS0QEl7UK2gdFFbHfNwuYlsq4H.jpg",
    },
    {
        id: 15,
        title: "Black Crab",
        trailerSrc: "https://www.youtube.com/embed/fmjKsL_-rfw",
        duration: 114,
        dateAired: "03/18/2022",
        ratingImdb: 5.7,
        description:
            "In a post-apocalyptic world, six soldiers on a covert mission must transport a mysterious package across a frozen archipelago.",
        photoSrc: "http://localhost:4000/images/movies/blackcrab.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/movies/blackcrab.jpg",
    },
    {
        id: 16,
        title: "The Extra Man",
        trailerSrc: "https://www.youtube.com/embed/etxKmplTT9Q",
        duration: 108,
        dateAired: "07/30/2010",
        ratingImdb: 5.8,
        description: "A man who escorts wealthy women in Manhattan takes a young man under his wing.",
        photoSrc: "http://localhost:4000/images/movies/7RhiXoCm6yEflHQvYtoLeAkDhaU.jpg",
        photoSrcProd:
            "https://movielandia-avenger22s-projects.vercel.app/images/movies/7RhiXoCm6yEflHQvYtoLeAkDhaU.jpg",
    },
    {
        id: 17,
        title: "14 Peaks: Nothing Is Impossible",
        trailerSrc: "https://www.youtube.com/embed/8QH5hBOoz08",
        duration: 101,
        dateAired: "12/09/2021",
        ratingImdb: 7.8,
        description:
            "Fearless Nepali mountaineer Nirmal Purja embarks on a seemingly impossible quest to summit all 14 of the world's 8,000-meter peaks in seven months.",
        photoSrc: "http://localhost:4000/images/movies/beyondpossible.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/movies/beyondpossible.jpg",
    },
    {
        id: 18,
        title: "The Innocents",
        trailerSrc: "https://www.youtube.com/embed/T8HR-zTRrCM",
        duration: 117,
        dateAired: "06/26/2021",
        ratingImdb: 7,
        description:
            "During the long days of the polar summer, a group of children reveal their dark and mysterious powers while the adults aren't watching. This playtime takes a dangerous turn.",
        photoSrc: "http://localhost:4000/images/movies/4hIptu4Yre7pIUhFa7GBZlfDTPW.jpg",
        photoSrcProd:
            "https://movielandia-avenger22s-projects.vercel.app/images/movies/4hIptu4Yre7pIUhFa7GBZlfDTPW.jpg",
    },
    {
        id: 19,
        title: "Mean Dreams",
        trailerSrc: "https://www.youtube.com/embed/jNOAVTX8PPE",
        duration: 108,
        dateAired: "05/20/2016",
        ratingImdb: 6.1,
        description:
            "A 15-year-old boy steals a bag of drug money and runs off with the girl he loves. As her violent and corrupt police officer father hunts them down, they embark on a journey that will change their lives forever.",
        photoSrc: "http://localhost:4000/images/movies/AlowOYyprAAq85PPtE9LvoiYT1b.jpg",
        photoSrcProd:
            "https://movielandia-avenger22s-projects.vercel.app/images/movies/AlowOYyprAAq85PPtE9LvoiYT1b.jpg",
    },
];

export const series = [
    {
        id: 1,
        title: "Rebelde",
        trailerSrc: "https://www.youtube.com/watch?v=BJYJksHREIc",
        description:
            "Rebelde follows the lives of students at Elite Way School, a prestigious private school in Mexico City.",
        dateAired: "01/05/2004",
        ratingImdb: 6.3,
        photoSrc: "http://localhost:4000/images/series/rebelde.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/rebelde.jpg",
    },
    {
        id: 2,
        title: "Snowfall",
        trailerSrc: "https://www.youtube.com/embed/BJYJksHREIc",
        description:
            "Snowfall is an American television series created by John Singleton, Eric Amadio, and Dave Andron. The series is set in the early 1980s in Los Angeles and examines the early days of the crack cocaine epidemic and its impact.",
        dateAired: "07/05/2017",
        ratingImdb: 8.2,
        photoSrc: "http://localhost:4000/images/series/snowfall.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/snowfall.jpg",
    },
    {
        id: 3,
        title: "Man vs Bee",
        trailerSrc: "https://www.youtube.com/embed/BJYJksHREIc",
        description:
            "Man vs Bee is a documentary series that explores the confrontation between plants and bees in our world.",
        dateAired: "06/24/2022",
        ratingImdb: 6.8,
        photoSrc: "http://localhost:4000/images/series/manbee.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/manbee.jpg",
    },
    {
        id: 4,
        title: "Moonknight",
        trailerSrc: "https://www.youtube.com/embed/x7Krla_UxRg",
        description:
            "Moonknight follows the adventures of Marc Spector, a former military man who gains powers from a mythological being.",
        dateAired: "03/30/2022",
        ratingImdb: 7.4,
        photoSrc: "http://localhost:4000/images/series/moonknight.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/moonknight.jpg",
    },
    {
        id: 5,
        title: "Peacemaker",
        trailerSrc: "https://www.youtube.com/embed/WHXq62VCaCM",
        description:
            "Peacemaker is an American television series created by James Gunn for the DC Universe and HBO Max.",
        dateAired: "01/13/2022",
        ratingImdb: 8.3,
        photoSrc: "http://localhost:4000/images/series/peacemaker.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/peacemaker.jpg",
    },
    {
        id: 6,
        title: "Top Boy",
        trailerSrc: "https://www.youtube.com/embed/BYLYZ7OsymE",
        description:
            "Top Boy is a British television series created by Ronan Bennet. The series follows the lives of teenagers and those involved in drug trafficking in a poor neighborhood in London.",
        dateAired: "10/31/2011",
        ratingImdb: 8.4,
        photoSrc: "http://localhost:4000/images/series/topboy.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/topboy.jpg",
    },
    {
        id: 7,
        title: "Ganglands",
        trailerSrc: "https://www.youtube.com/embed/0VZ2Nbx8gHI",
        description:
            "Ganglands is a French crime series based on the true story of a family running an organized crime gang in Paris.",
        dateAired: "09/24/2021",
        ratingImdb: 7.0,
        photoSrc: "http://localhost:4000/images/series/ganglands.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/ganglands.jpg",
    },
    {
        id: 8,
        title: "Ozark",
        trailerSrc: "https://www.youtube.com/embed/5hAXVqrljbs",
        description:
            "Ozark is an American drama series that follows the life of a family that develops a large money-laundering business in the Ozark Mountains in Missouri.",
        dateAired: "07/21/2017",
        ratingImdb: 8.5,
        photoSrc: "http://localhost:4000/images/series/ozark.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/ozark.jpg",
    },
    {
        id: 9,
        title: "Resident Alien",
        trailerSrc: "https://www.youtube.com/embed/T4J7QjGNTs4",
        description:
            "Resident Alien is an American sci-fi comedy series that follows an extraterrestrial trying to escape his secret identity by living as a doctor in a small American town.",
        dateAired: "01/27/2021",
        ratingImdb: 8.1,
        photoSrc: "http://localhost:4000/images/series/alien.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/alien.jpg",
    },
    {
        id: 10,
        title: "Bridgerton",
        trailerSrc: "https://www.youtube.com/embed/U4JYAx5rNRA",
        description:
            "Bridgerton is a British-American historical drama series created by Chris Van Dusen and produced by Shonda Rhimes. The series follows the lives of the Bridgerton family in London from 1813-1827.",
        dateAired: "12/25/2020",
        ratingImdb: 7.3,
        photoSrc: "http://localhost:4000/images/series/bridgerton.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/bridgerton.jpg",
    },
    {
        id: 11,
        title: "Superman and Lois",
        trailerSrc: "https://www.youtube.com/embed/SJPJPUpNvDw",
        description:
            "Superman & Lois is an American superhero television series based on the DC Comics characters Superman and Lois Lane. The series follows the lives of Superman and Lois Lane after their marriage, facing challenges in both their personal lives and their profession as superheroes.",
        dateAired: "02/23/2021",
        ratingImdb: 7.8,
        photoSrc: "http://localhost:4000/images/series/superman.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/superman.jpg",
    },
    {
        id: 12,
        title: "Attack on Titan",
        trailerSrc: "https://www.youtube.com/embed/MGRm4IzK1SQ",
        description:
            "Attack on Titan is a Japanese anime series based on the manga of the same name written by Hajime Isayama. The series follows the story of a world where human civilization is threatened by giant creatures known as Titans.",
        dateAired: "04/07/2013",
        ratingImdb: 9.0,
        photoSrc: "http://localhost:4000/images/series/aot.png",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/aot.png",
    },
    {
        id: 13,
        title: "Kengan Ashura",
        trailerSrc: "https://www.youtube.com/embed/CNuY4ymi4Fs",
        description:
            "Kengan Ashura is a Japanese anime series based on the manga of the same name written by Yabako Sandrovich. The series follows the story of Tokita Ohma, a young fighter involved in a combat tournament called Kengan to dominate the business of firms.",
        dateAired: "07/31/2019",
        ratingImdb: 8.0,
        photoSrc: "http://localhost:4000/images/series/baki.png",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/baki.png",
    },
    {
        id: 14,
        title: "Elite",
        trailerSrc: "https://www.youtube.com/embed/QNwhAdrdwp0",
        description:
            "Elite is a Spanish series created by Carlos Montero and Darío Madrona. The series follows the lives of students at a high-end private school in Spain, where tragic events and various secrets come to light.",
        dateAired: "10/05/2018",
        ratingImdb: 7.4,
        photoSrc: "http://localhost:4000/images/series/elite.png",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/elite.png",
    },
    {
        id: 15,
        title: "The Flash",
        trailerSrc: "https://www.youtube.com/embed/hebWYacbdvc",
        description:
            "The Flash is an American superhero television series created by Greg Berlanti, Andrew Kreisberg, and Geoff Johns, based on the DC Comics character of the same name. The series follows the adventures of Barry Allen, a forensic scientist who gains the ability to move at incredible speeds after a lab accident.",
        dateAired: "10/07/2014",
        ratingImdb: 7.6,
        photoSrc: "http://localhost:4000/images/series/flash.png",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/flash.png",
    },
    {
        id: 16,
        title: "Power Book IV Force",
        trailerSrc: "https://www.youtube.com/embed/uiGzLrJSk8E",
        description:
            'Power Book IV: Force is an American drama series created by Courtney A. Kemp for Starz. The series follows the life of Tommy Egan, a character first introduced in the series "Power", as he becomes involved in the world of organized crime in Chicago.',
        dateAired: "02/06/2022",
        ratingImdb: 8.1,
        photoSrc: "http://localhost:4000/images/series/force.png",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/force.png",
    },
    {
        id: 17,
        title: "Halo",
        trailerSrc: "https://www.youtube.com/embed/5KZ3MKraNKY",
        description:
            'Halo is an American sci-fi television series created by Kyle Killen and Steven Kane. Based on the popular "Halo" video game by Microsoft Studios, the series follows the adventures of Master Chief, a super-soldier called upon to protect a harsh world from the threat of an alien alliance known as the Covenant.',
        dateAired: "03/24/2022",
        ratingImdb: 7.0,
        photoSrc: "http://localhost:4000/images/series/halo.png",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/halo.png",
    },
    {
        id: 18,
        title: "The Last Kingdom",
        trailerSrc: "https://www.youtube.com/embed/BJYJksHREIc",
        description:
            'The Last Kingdom is a British historical series created by Stephen Butchard. Based on the "Saxon Stories" novels by Bernard Cornwell, the series follows the adventures of Uhtred Ragnarson, a Saxon boy who attempts to defend and reclaim his territory in Middle Britain in the 9th century.',
        dateAired: "10/10/2015",
        ratingImdb: 8.5,
        photoSrc: "http://localhost:4000/images/series/kingdom.png",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/kingdom.png",
    },
    {
        id: 19,
        title: "Knightfall",
        trailerSrc: "https://www.youtube.com/embed/F9dtepkeR0I",
        description:
            "Knightfall is an American historical drama series created by Don Handfield and Richard Rayner for the History Channel. The series follows the rise and fall of the Knights Templar, beginning with its foundation in post-war Selma, Alabama, in 1865, to its suppression in 1871.",
        dateAired: "12/06/2017",
        ratingImdb: 6.7,
        photoSrc: "http://localhost:4000/images/series/knightfall.png",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/knightfall.png",
    },
];

export const seasons = [
    {
        id: 1,
        title: "Rebelde S01",
        photoSrc: "http://localhost:4000/images/series/rebelde.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/rebelde.jpg",
        description: "Description for Season 1 in Rebelde.",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        dateAired: "01/01/2000",
        ratingImdb: 5.5,
        serieId: 1,
    },
    {
        id: 2,
        title: "Snowfall S01",
        photoSrc: "http://localhost:4000/images/series/snowfall.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/snowfall.jpg",
        description: "Description for Season 1 in Snowfall.",
        trailerSrc: "https://www.youtube.com/embed/7GdM7gZ1ip4",
        dateAired: "01/01/2000",
        ratingImdb: 5.3,
        serieId: 2,
    },
    {
        id: 3,
        title: "Man vs Bee S01",
        photoSrc: "http://localhost:4000/images/series/manbee.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/manbee.jpg",
        description: "Description for Season 1 in Man vs Bee.",
        trailerSrc: "https://www.youtube.com/embed/Dm5Y0g4u4DU",
        dateAired: "01/01/2000",
        ratingImdb: 5.7,
        serieId: 3,
    },
    {
        id: 4,
        title: "Man vs Bee S02",
        photoSrc: "http://localhost:4000/images/series/manbee.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/manbee.jpg",
        description: "Description for Season 2 in Man vs Bee.",
        trailerSrc: "https://www.youtube.com/embed/PA8OQX4qW0M",
        dateAired: "01/01/2000",
        ratingImdb: 5.0,
        serieId: 3,
    },
    {
        id: 5,
        title: "Moonknight S01",
        photoSrc: "http://localhost:4000/images/series/moonknight.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/moonknight.jpg",
        description: "Description for Season 1 in Moonknight.",
        trailerSrc: "https://www.youtube.com/embed/qx6PbFC-8bM",
        dateAired: "01/01/2000",
        ratingImdb: 5.2,
        serieId: 4,
    },
    {
        id: 6,
        title: "Moonknight S02",
        photoSrc: "http://localhost:4000/images/series/moonknight.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/moonknight.jpg",
        description: "Description for Season 2 in Moonknight.",
        trailerSrc: "https://www.youtube.com/embed/N4k9EFdxFCk",
        dateAired: "01/01/2000",
        ratingImdb: 5.5,
        serieId: 4,
    },
    {
        id: 7,
        title: "Peacemaker S01",
        photoSrc: "http://localhost:4000/images/series/peacemaker.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/peacemaker.jpg",
        description: "Description for Season 1 in Peacemaker.",
        trailerSrc: "https://www.youtube.com/embed/8-VpHwnh4d4",
        dateAired: "01/01/2000",
        ratingImdb: 5.8,
        serieId: 5,
    },
    {
        id: 8,
        title: "Peacemaker S02",
        photoSrc: "http://localhost:4000/images/series/peacemaker.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/peacemaker.jpg",
        description: "Description for Season 2 in Peacemaker.",
        trailerSrc: "https://www.youtube.com/embed/LeZTlvK7BR4",
        dateAired: "01/01/2000",
        ratingImdb: 5.5,
        serieId: 5,
    },
    {
        id: 9,
        title: "Top Boy S01",
        photoSrc: "http://localhost:4000/images/series/topboy.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/topboy.jpg",
        description: "Description for Season 1 in Top Boy.",
        trailerSrc: "https://www.youtube.com/embed/2gRFDx6Cz7k",
        dateAired: "01/01/2000",
        ratingImdb: 5.0,
        serieId: 6,
    },
    {
        id: 10,
        title: "Ganglands S01",
        photoSrc: "http://localhost:4000/images/series/ganglands.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/ganglands.jpg",
        description: "Description for Season 1 in Ganglands.",
        trailerSrc: "https://www.youtube.com/embed/v1GcRDY-S5Y",
        dateAired: "01/01/2000",
        ratingImdb: 5.6,
        serieId: 7,
    },
    {
        id: 11,
        title: "Ganglands S02",
        photoSrc: "http://localhost:4000/images/series/ganglands.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/ganglands.jpg",
        description: "Description for Season 2 in Ganglands.",
        trailerSrc: "https://www.youtube.com/embed/WF9mGrcKnU8",
        dateAired: "01/01/2000",
        ratingImdb: 6.1,
        serieId: 7,
    },
    {
        id: 12,
        title: "Ozark S01",
        photoSrc: "http://localhost:4000/images/series/ozark.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/ozark.jpg",
        description: "Description for Season 1 in Ozark.",
        trailerSrc: "https://www.youtube.com/embed/Jmco5ErG2Zk",
        dateAired: "01/01/2000",
        ratingImdb: 6.1,
        serieId: 8,
    },
    {
        id: 13,
        title: "Resident Alien S01",
        photoSrc: "http://localhost:4000/images/series/alien.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/alien.jpg",
        description: "Description for Season 1 in Resident Alien.",
        trailerSrc: "https://www.youtube.com/embed/mC7GJyt3gD4",
        dateAired: "01/01/2000",
        ratingImdb: 5.5,
        serieId: 9,
    },
    {
        id: 14,
        title: "Bridgerton S01",
        photoSrc: "http://localhost:4000/images/series/bridgerton.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/bridgerton.jpg",
        description: "Description for Season 1 in Bridgerton.",
        trailerSrc: "https://www.youtube.com/embed/2uBCt7AvHsQ",
        dateAired: "01/01/2000",
        ratingImdb: 5.9,
        serieId: 10,
    },
    {
        id: 15,
        title: "Bridgerton S02",
        photoSrc: "http://localhost:4000/images/series/bridgerton.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/bridgerton.jpg",
        description: "Description for Season 2 in Bridgerton.",
        trailerSrc: "https://www.youtube.com/embed/BDHBDtKFrGQ",
        dateAired: "01/01/2000",
        ratingImdb: 5.6,
        serieId: 10,
    },
    {
        id: 16,
        title: "Superman and Lois S01",
        photoSrc: "http://localhost:4000/images/series/superman.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/superman.jpg",
        description: "Description for Season 1 in Superman & Lois.",
        trailerSrc: "https://www.youtube.com/embed/mXjpZy0j8_M",
        dateAired: "01/01/2000",
        ratingImdb: 5.9,
        serieId: 11,
    },
    {
        id: 17,
        title: "Superman and Lois S02",
        photoSrc: "http://localhost:4000/images/series/superman.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/superman.jpg",
        description: "Description for Season 2 in Superman & Lois.",
        trailerSrc: "https://www.youtube.com/embed/Kte1K7nGFts",
        dateAired: "01/01/2000",
        ratingImdb: 5.3,
        serieId: 11,
    },
    {
        id: 18,
        title: "Attack on Titan S01",
        photoSrc: "http://localhost:4000/images/series/aot.png",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/aot.png",
        description: "Description for Season 1 in Attack on Titan.",
        trailerSrc: "https://www.youtube.com/embed/0lEWTieGV3U",
        dateAired: "01/01/2000",
        ratingImdb: 6.3,
        serieId: 12,
    },
    {
        id: 19,
        title: "Kengan Ashura S01",
        photoSrc: "http://localhost:4000/images/series/baki.png",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/baki.png",
        description: "Description for Season 1 in Kengan Ashura.",
        trailerSrc: "https://www.youtube.com/embed/4QMY0fxaDQ0",
        dateAired: "01/01/2000",
        ratingImdb: 5.5,
        serieId: 13,
    },
    {
        id: 20,
        title: "Elite S01",
        photoSrc: "http://localhost:4000/images/series/elite.png",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/elite.png",
        description: "Description for Season 1 in Elite.",
        trailerSrc: "https://www.youtube.com/embed/xrcd1tVbK7Y",
        dateAired: "01/01/2000",
        ratingImdb: 5.8,
        serieId: 14,
    },
    {
        id: 21,
        title: "Elite S02",
        photoSrc: "http://localhost:4000/images/series/elite.png",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/elite.png",
        description: "Description for Season 2 in Elite.",
        trailerSrc: "https://www.youtube.com/embed/8-CKQ_X5Fz4",
        dateAired: "01/01/2000",
        ratingImdb: 5.4,
        serieId: 14,
    },
    {
        id: 22,
        title: "The Flash S01",
        photoSrc: "http://localhost:4000/images/series/flash.png",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/flash.png",
        description: "Description for Season 1 in The Flash.",
        trailerSrc: "https://www.youtube.com/embed/RLckrnS9O4E",
        dateAired: "01/01/2000",
        ratingImdb: 5.2,
        serieId: 15,
    },
    {
        id: 23,
        title: "Power Book IV Force S01",
        photoSrc: "http://localhost:4000/images/series/force.png",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/force.png",
        description: "Description for Season 1 in Power Book IV Force.",
        trailerSrc: "https://www.youtube.com/embed/Ey6afOM2TbI",
        dateAired: "01/01/2000",
        ratingImdb: 5.0,
        serieId: 16,
    },
    {
        id: 24,
        title: "Power Book IV Force S02",
        photoSrc: "http://localhost:4000/images/series/force.png",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/force.png",
        description: "Description for Season 2 in Power Book IV Force.",
        trailerSrc: "https://www.youtube.com/embed/LugI0VymBsQ",
        dateAired: "01/01/2000",
        ratingImdb: 6.4,
        serieId: 16,
    },
    {
        id: 25,
        title: "Halo S01",
        photoSrc: "http://localhost:4000/images/series/halo.png",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/halo.png",
        description: "Description for Season 1 in Halo.",
        trailerSrc: "https://www.youtube.com/embed/7FfdSuZq0hw",
        dateAired: "01/01/2000",
        ratingImdb: 5.8,
        serieId: 17,
    },
    {
        id: 26,
        title: "The Last Kingdom S01",
        photoSrc: "http://localhost:4000/images/series/kingdom.png",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/kingdom.png",
        description: "Description for Season 1 in The Last Kingdom.",
        trailerSrc: "https://www.youtube.com/embed/4ayIztm4BL4",
        dateAired: "01/01/2000",
        ratingImdb: 6.1,
        serieId: 18,
    },
    {
        id: 27,
        title: "Knightfall S01",
        photoSrc: "http://localhost:4000/images/series/knightfall.png",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/knightfall.png",
        description: "Description for Season 1 in Knightfall.",
        trailerSrc: "https://www.youtube.com/embed/CrF8A6uZ2fA",
        dateAired: "01/01/2000",
        ratingImdb: 6.4,
        serieId: 19,
    },
    {
        id: 28,
        title: "Knightfall S02",
        photoSrc: "http://localhost:4000/images/series/knightfall.png",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/knightfall.png",
        description: "Description for Season 2 in Knightfall.",
        trailerSrc: "https://www.youtube.com/embed/Ma8XxR5Fj54",
        dateAired: "01/01/2000",
        ratingImdb: 5.5,
        serieId: 19,
    },
];

export const episodes = [
    {
        id: 1,
        title: "Rebelde S01 E01",
        photoSrc: "http://localhost:4000/images/series/rebelde.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/rebelde.jpg",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 15,
        description: "Description for Episode 1 of Season 1 in Rebelde.",
        dateAired: "01/01/2023",
        ratingImdb: 6,
        seasonId: 1,
    },
    {
        id: 2,
        title: "Snowfall S01 E01",
        photoSrc: "http://localhost:4000/images/series/snowfall.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/snowfall.jpg",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 15,
        description: "Description for Episode 1 of Season 1 in Snowfall.",
        dateAired: "06/07/2021",
        ratingImdb: 5.6,
        seasonId: 2,
    },
    {
        id: 3,
        title: "Snowfall S01 E02",
        photoSrc: "http://localhost:4000/images/series/snowfall.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/snowfall.jpg",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 15,
        description: "Description for Episode 2 of Season 1 in Snowfall.",
        dateAired: "13/07/2021",
        ratingImdb: 5.2,
        seasonId: 2,
    },
    {
        id: 4,
        title: "Man vs Bee S01 E01",
        photoSrc: "http://localhost:4000/images/series/manbee.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/manbee.jpg",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 24,
        description: "Description for Episode 1 of Season 1 in Man vs Bee.",
        dateAired: "11/06/2022",
        ratingImdb: 6.2,
        seasonId: 3,
    },
    {
        id: 5,
        title: "Man vs Bee S01 E02",
        photoSrc: "http://localhost:4000/images/series/manbee.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/manbee.jpg",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 42,
        description: "Description for Episode 2 of Season 1 in Man vs Bee.",
        dateAired: "18/06/2022",
        ratingImdb: 5.2,
        seasonId: 3,
    },
    {
        id: 6,
        title: "Man vs Bee S02 E01",
        photoSrc: "http://localhost:4000/images/series/manbee.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/manbee.jpg",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 31,
        description: "Description for Episode 1 of Season 2 in Man vs Bee.",
        dateAired: "01/01/2023",
        ratingImdb: 6.5,
        seasonId: 4,
    },
    {
        id: 7,
        title: "Man vs Bee S01 E02",
        photoSrc: "http://localhost:4000/images/series/manbee.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/manbee.jpg",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 15,
        description: "Description for Episode 2 of Season 2 in Man vs Bee.",
        dateAired: "08/01/2023",
        ratingImdb: 5.1,
        seasonId: 4,
    },
    {
        id: 8,
        title: "Moonknight S01 E01",
        photoSrc: "http://localhost:4000/images/series/moonknight.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/moonknight.jpg",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 39,
        description: "Description for Episode 1 of Season 1 in Moonknight.",
        dateAired: "30/03/2022",
        ratingImdb: 6.4,
        seasonId: 5,
    },
    {
        id: 9,
        title: "Moonknight S01 E02",
        photoSrc: "http://localhost:4000/images/series/moonknight.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/moonknight.jpg",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 23,
        description: "Description for Episode 2 of Season 1 in Moonknight.",
        dateAired: "06/04/2022",
        ratingImdb: 6.2,
        seasonId: 5,
    },
    {
        id: 10,
        title: "Moonknight S02 E01",
        photoSrc: "http://localhost:4000/images/series/moonknight.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/moonknight.jpg",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 38,
        description: "Description for Episode 1 of Season 2 in Moonknight.",
        dateAired: "01/01/2024",
        ratingImdb: 5.9,
        seasonId: 6,
    },
    {
        id: 11,
        title: "Moonknight S02 E02",
        photoSrc: "http://localhost:4000/images/series/moonknight.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/moonknight.jpg",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 40,
        description: "Description for Episode 2 of Season 2 in Moonknight.",
        dateAired: "08/01/2024",
        ratingImdb: 5.8,
        seasonId: 6,
    },
    {
        id: 12,
        title: "Peacemaker S01 E01",
        photoSrc: "http://localhost:4000/images/series/peacemaker.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/peacemaker.jpg",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 15,
        description: "Description for Episode 1 of Season 1 in Peacemaker.",
        dateAired: "13/01/2022",
        ratingImdb: 5.6,
        seasonId: 7,
    },
    {
        id: 13,
        title: "Peacemaker S01 E02",
        photoSrc: "http://localhost:4000/images/series/peacemaker.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/peacemaker.jpg",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 15,
        description: "Description for Episode 2 of Season 1 in Peacemaker.",
        dateAired: "20/01/2022",
        ratingImdb: 5.2,
        seasonId: 7,
    },
    {
        id: 14,
        title: "Peacemaker S02 E01",
        photoSrc: "http://localhost:4000/images/series/peacemaker.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/peacemaker.jpg",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 39,
        description: "Description for Episode 1 of Season 2 in Peacemaker.",
        dateAired: "01/01/2024",
        ratingImdb: 5.4,
        seasonId: 8,
    },
    {
        id: 15,
        title: "Top Boy S01 E01",
        photoSrc: "http://localhost:4000/images/series/topboy.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/topboy.jpg",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 15,
        description: "Description for Episode 1 of Season 1 in Top Boy.",
        dateAired: "20/02/2023",
        ratingImdb: 5.8,
        seasonId: 9,
    },
    {
        id: 16,
        title: "Top Boy S01 E02",
        photoSrc: "http://localhost:4000/images/series/topboy.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/topboy.jpg",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 41,
        description: "Description for Episode 2 of Season 1 in Top Boy.",
        dateAired: "27/02/2023",
        ratingImdb: 5.5,
        seasonId: 9,
    },
    {
        id: 17,
        title: "Ganglands S01 E01",
        photoSrc: "http://localhost:4000/images/series/ganglands.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/ganglands.jpg",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 25,
        description: "Description for Episode 1 of Season 1 in Ganglands.",
        dateAired: "01/11/2021",
        ratingImdb: 5.9,
        seasonId: 10,
    },
    {
        id: 18,
        title: "Ganglands S02 E01",
        photoSrc: "http://localhost:4000/images/series/ganglands.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/ganglands.jpg",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 15,
        description: "Description for Episode 1 of Season 2 in Ganglands.",
        dateAired: "01/01/2023",
        ratingImdb: 6.4,
        seasonId: 11,
    },
    {
        id: 19,
        title: "Ozark S01 E01",
        photoSrc: "http://localhost:4000/images/series/ozark.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/ozark.jpg",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 29,
        description: "Description for Episode 1 of Season 1 in Ozark.",
        dateAired: "21/03/2017",
        ratingImdb: 5.3,
        seasonId: 12,
    },
    {
        id: 20,
        title: "Resident Alien S01 E01",
        photoSrc: "http://localhost:4000/images/series/alien.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/alien.jpg",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 36,
        description: "Description for Episode 1 of Season 1 in Resident Alien.",
        dateAired: "27/01/2021",
        ratingImdb: 5.5,
        seasonId: 13,
    },
    {
        id: 21,
        title: "Resident Alien S01 E02",
        photoSrc: "http://localhost:4000/images/series/alien.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/alien.jpg",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 30,
        description: "Description for Episode 2 of Season 1 in Resident Alien.",
        dateAired: "03/02/2021",
        ratingImdb: 6,
        seasonId: 13,
    },
    {
        id: 22,
        title: "Bridgerton S01 E01",
        photoSrc: "http://localhost:4000/images/series/bridgerton.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/bridgerton.jpg",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 35,
        description: "Description for Episode 1 of Season 1 in Bridgerton.",
        dateAired: "25/12/2020",
        ratingImdb: 5.4,
        seasonId: 14,
    },
    {
        id: 23,
        title: "Bridgerton S01 E02",
        photoSrc: "http://localhost:4000/images/series/bridgerton.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/bridgerton.jpg",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 18,
        description: "Description for Episode 2 of Season 1 in Bridgerton.",
        dateAired: "01/01/2021",
        ratingImdb: 5.8,
        seasonId: 14,
    },
    {
        id: 24,
        title: "Bridgerton S02 E01",
        photoSrc: "http://localhost:4000/images/series/bridgerton.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/bridgerton.jpg",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 31,
        description: "Description for Episode 1 of Season 2 in Bridgerton.",
        dateAired: "25/03/2022",
        ratingImdb: 5.4,
        seasonId: 15,
    },
    {
        id: 25,
        title: "Superman and Lois S01 E01",
        photoSrc: "http://localhost:4000/images/series/superman.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/superman.jpg",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 16,
        description: "Description for Episode 1 of Season 1 in Superman and Lois.",
        dateAired: "23/02/2021",
        ratingImdb: 5.1,
        seasonId: 16,
    },
    {
        id: 26,
        title: "Superman and Lois S01 E02",
        photoSrc: "http://localhost:4000/images/series/superman.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/superman.jpg",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 15,
        description: "Description for Episode 2 of Season 1 in Superman and Lois.",
        dateAired: "02/03/2021",
        ratingImdb: 5.7,
        seasonId: 16,
    },
    {
        id: 27,
        title: "Superman and Lois S02 E01",
        photoSrc: "http://localhost:4000/images/series/superman.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/superman.jpg",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 37,
        description: "Description for Episode 1 of Season 2 in Superman and Lois.",
        dateAired: "01/01/2023",
        ratingImdb: 5.9,
        seasonId: 17,
    },
    {
        id: 28,
        title: "Attack on Titan S01 E01",
        photoSrc: "http://localhost:4000/images/series/aot.png",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/aot.png",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 35,
        description: "Description for Episode 1 of Season 1 in Attack on Titan.",
        dateAired: "07/04/2013",
        ratingImdb: 5.3,
        seasonId: 18,
    },
    {
        id: 29,
        title: "Kengan Ashura S01 E01",
        photoSrc: "http://localhost:4000/images/series/baki.png",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/baki.png",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 20,
        description: "Description for Episode 1 of Season 1 in Kengan Ashura.",
        dateAired: "31/12/2019",
        ratingImdb: 5.8,
        seasonId: 19,
    },
    {
        id: 30,
        title: "Elite S01 E01",
        photoSrc: "http://localhost:4000/images/series/elite.png",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/elite.png",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 15,
        description: "Description for Episode 1 of Season 1 in Elite.",
        dateAired: "05/10/2018",
        ratingImdb: 5,
        seasonId: 20,
    },
    {
        id: 31,
        title: "Elite S01 E02",
        photoSrc: "http://localhost:4000/images/series/elite.png",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/elite.png",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 39,
        description: "Description for Episode 2 of Season 1 in Elite.",
        dateAired: "12/10/2018",
        ratingImdb: 5.1,
        seasonId: 20,
    },
    {
        id: 32,
        title: "Elite S02 E01",
        photoSrc: "http://localhost:4000/images/series/elite.png",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/elite.png",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 20,
        description: "Description for Episode 1 of Season 2 in Elite.",
        dateAired: "06/09/2019",
        ratingImdb: 5.8,
        seasonId: 21,
    },
    {
        id: 33,
        title: "Elite S02 E02",
        photoSrc: "http://localhost:4000/images/series/elite.png",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/elite.png",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 24,
        description: "Description for Episode 2 of Season 2 in Elite.",
        dateAired: "13/09/2019",
        ratingImdb: 5.7,
        seasonId: 21,
    },
    {
        id: 34,
        title: "The Flash S01 E01",
        photoSrc: "http://localhost:4000/images/series/flash.png",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/flash.png",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 30,
        description: "Description for Episode 1 of Season 1 in The Flash.",
        dateAired: "08/10/2014",
        ratingImdb: 5.5,
        seasonId: 22,
    },
    {
        id: 35,
        title: "The Flash S01 E02",
        photoSrc: "http://localhost:4000/images/series/flash.png",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/flash.png",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 44,
        description: "Description for Episode 2 of Season 1 in The Flash.",
        dateAired: "15/10/2014",
        ratingImdb: 6.3,
        seasonId: 22,
    },
    {
        id: 36,
        title: "Power Book IV Force S01 E01",
        photoSrc: "http://localhost:4000/images/series/force.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/force.jpg",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 15,
        description: "Description for Episode 1 of Season 1 in Power Book IV Force.",
        dateAired: "06/02/2022",
        ratingImdb: 5.7,
        seasonId: 23,
    },
    {
        id: 37,
        title: "Power Book IV Force S01 E02",
        photoSrc: "http://localhost:4000/images/series/force.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/force.jpg",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 38,
        description: "Description for Episode 2 of Season 1 in Power Book IV Force.",
        dateAired: "13/02/2022",
        ratingImdb: 6.5,
        seasonId: 23,
    },
    {
        id: 38,
        title: "Power Book IV Force S02 E01",
        photoSrc: "http://localhost:4000/images/series/force.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/force.jpg",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 26,
        description: "Description for Episode 1 of Season 2 in Power Book IV Force.",
        dateAired: "01/01/2023",
        ratingImdb: 5.3,
        seasonId: 24,
    },
    {
        id: 39,
        title: "Halo S01 E01",
        photoSrc: "http://localhost:4000/images/series/halo.png",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/halo.png",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 30,
        description: "Description for Episode 1 of Season 1 in Halo.",
        dateAired: "24/03/2022",
        ratingImdb: 5.2,
        seasonId: 25,
    },
    {
        id: 40,
        title: "The Last Kingdom S01 E01",
        photoSrc: "http://localhost:4000/images/series/kingdom.png",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/kingdom.png",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 29,
        description: "Description for Episode 1 of Season 1 in The Last Kingdom.",
        dateAired: "10/10/2015",
        ratingImdb: 6.4,
        seasonId: 26,
    },
    {
        id: 41,
        title: "The Last Kingdom S01 E02",
        photoSrc: "http://localhost:4000/images/series/kingdom.png",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/kingdom.png",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 15,
        description: "Description for Episode 2 of Season 1 in The Last Kingdom.",
        dateAired: "17/10/2015",
        ratingImdb: 5.2,
        seasonId: 26,
    },
    {
        id: 42,
        title: "Knightfall S01 E01",
        photoSrc: "http://localhost:4000/images/series/knightfall.png",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/knightfall.png",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 15,
        description: "Description for Episode 1 of Season 1 in Knightfall.",
        dateAired: "06/12/2017",
        ratingImdb: 5.1,
        seasonId: 27,
    },
    {
        id: 43,
        title: "Knightfall S01 E02",
        photoSrc: "http://localhost:4000/images/series/knightfall.png",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/knightfall.png",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 16,
        description: "Description for Episode 2 of Season 1 in Knightfall.",
        dateAired: "13/12/2017",
        ratingImdb: 6.3,
        seasonId: 27,
    },
    {
        id: 44,
        title: "Knightfall S02 E01",
        photoSrc: "http://localhost:4000/images/series/knightfall.png",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/series/knightfall.png",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: 18,
        description: "Description for Episode 1 of Season 2 in Knightfall.",
        dateAired: "06/03/2019",
        ratingImdb: 5.5,
        seasonId: 28,
    },
];

export const movieGenres = [
    { movieId: 1, genreId: 1 },
    { movieId: 1, genreId: 2 },
    { movieId: 2, genreId: 3 },
    { movieId: 2, genreId: 4 },
    { movieId: 2, genreId: 5 },
    { movieId: 3, genreId: 6 },
    { movieId: 3, genreId: 7 },
    { movieId: 4, genreId: 8 },
    { movieId: 4, genreId: 9 },
    { movieId: 4, genreId: 10 },
    { movieId: 5, genreId: 11 },
    { movieId: 5, genreId: 12 },
    { movieId: 5, genreId: 13 },
    { movieId: 6, genreId: 14 },
    { movieId: 6, genreId: 15 },
    { movieId: 6, genreId: 16 },
    { movieId: 7, genreId: 17 },
    { movieId: 7, genreId: 18 },
    { movieId: 7, genreId: 19 },
    { movieId: 8, genreId: 20 },
    { movieId: 8, genreId: 21 },
    { movieId: 8, genreId: 22 },
    { movieId: 9, genreId: 23 },
    { movieId: 9, genreId: 24 },
    { movieId: 10, genreId: 25 },
    { movieId: 11, genreId: 26 },
    { movieId: 11, genreId: 27 },
    { movieId: 11, genreId: 28 },
    { movieId: 11, genreId: 29 },
    { movieId: 12, genreId: 30 },
    { movieId: 13, genreId: 31 },
    { movieId: 14, genreId: 3 },
    { movieId: 15, genreId: 1 },
    { movieId: 15, genreId: 2 },
    { movieId: 15, genreId: 3 },
    { movieId: 15, genreId: 4 },
    { movieId: 15, genreId: 5 },
    { movieId: 16, genreId: 6 },
    { movieId: 16, genreId: 7 },
    { movieId: 16, genreId: 8 },
    { movieId: 16, genreId: 9 },
    { movieId: 16, genreId: 10 },
    { movieId: 17, genreId: 11 },
    { movieId: 17, genreId: 12 },
    { movieId: 18, genreId: 13 },
    { movieId: 18, genreId: 14 },
    { movieId: 19, genreId: 15 },
    { movieId: 19, genreId: 16 },
    { movieId: 19, genreId: 17 },
];

export const serieGenres = [
    { serieId: 1, genreId: 1 },
    { serieId: 1, genreId: 2 },
    { serieId: 1, genreId: 3 },
    { serieId: 2, genreId: 4 },
    { serieId: 2, genreId: 5 },
    { serieId: 3, genreId: 6 },
    { serieId: 3, genreId: 7 },
    { serieId: 5, genreId: 8 },
    { serieId: 4, genreId: 9 },
    { serieId: 6, genreId: 10 },
    { serieId: 6, genreId: 11 },
    { serieId: 6, genreId: 12 },
    { serieId: 6, genreId: 13 },
    { serieId: 7, genreId: 14 },
    { serieId: 7, genreId: 15 },
    { serieId: 7, genreId: 16 },
    { serieId: 7, genreId: 17 },
    { serieId: 8, genreId: 18 },
    { serieId: 10, genreId: 19 },
    { serieId: 9, genreId: 20 },
    { serieId: 11, genreId: 21 },
    { serieId: 12, genreId: 22 },
    { serieId: 13, genreId: 23 },
    { serieId: 14, genreId: 24 },
    { serieId: 15, genreId: 25 },
    { serieId: 16, genreId: 26 },
    { serieId: 17, genreId: 27 },
    { serieId: 18, genreId: 28 },
    { serieId: 19, genreId: 29 },
    { serieId: 19, genreId: 30 },
    { serieId: 19, genreId: 31 },
    { serieId: 19, genreId: 5 },
];

export const castMovies = [
    { id: 1, movieId: 5, actorId: 1 },
    { id: 2, movieId: 5, actorId: 2 },
    { id: 3, movieId: 5, actorId: 3 },
    { id: 4, movieId: 13, actorId: 4 },
    { id: 5, movieId: 13, actorId: 5 },
    { id: 6, movieId: 13, actorId: 6 },
    { id: 7, movieId: 14, actorId: 7 },
    { id: 8, movieId: 14, actorId: 8 },
    { id: 9, movieId: 1, actorId: 11 },
    { id: 10, movieId: 1, actorId: 12 },
    { id: 11, movieId: 1, actorId: 13 },
    { id: 12, movieId: 2, actorId: 14 },
    { id: 13, movieId: 2, actorId: 15 },
    { id: 14, movieId: 2, actorId: 16 },
    { id: 15, movieId: 3, actorId: 17 },
    { id: 16, movieId: 3, actorId: 18 },
    { id: 17, movieId: 3, actorId: 19 },
    { id: 18, movieId: 4, actorId: 20 },
    { id: 19, movieId: 4, actorId: 21 },
    { id: 20, movieId: 4, actorId: 22 },
    { id: 21, movieId: 6, actorId: 23 },
    { id: 22, movieId: 6, actorId: 24 },
    { id: 23, movieId: 6, actorId: 25 },
    { id: 24, movieId: 8, actorId: 26 },
    { id: 25, movieId: 8, actorId: 27 },
    { id: 26, movieId: 8, actorId: 28 },
    { id: 27, movieId: 9, actorId: 29 },
    { id: 28, movieId: 9, actorId: 30 },
    { id: 29, movieId: 9, actorId: 31 },
    { id: 30, movieId: 10, actorId: 32 },
    { id: 31, movieId: 10, actorId: 33 },
    { id: 32, movieId: 10, actorId: 34 },
    { id: 33, movieId: 15, actorId: 35 },
    { id: 34, movieId: 15, actorId: 36 },
    { id: 35, movieId: 15, actorId: 37 },
    { id: 36, movieId: 16, actorId: 38 },
    { id: 37, movieId: 16, actorId: 39 },
    { id: 38, movieId: 16, actorId: 40 },
];

export const castSeries = [
    { id: 1, serieId: 2, actorId: 9 },
    { id: 2, serieId: 2, actorId: 10 },
    { id: 3, serieId: 4, actorId: 3 },
    { id: 4, serieId: 8, actorId: 7 },
    { id: 5, serieId: 1, actorId: 41 },
    { id: 6, serieId: 1, actorId: 42 },
    { id: 7, serieId: 1, actorId: 43 },
    { id: 8, serieId: 3, actorId: 44 },
    { id: 9, serieId: 3, actorId: 45 },
    { id: 10, serieId: 3, actorId: 46 },
    { id: 11, serieId: 5, actorId: 37 },
    { id: 12, serieId: 5, actorId: 38 },
    { id: 13, serieId: 5, actorId: 39 },
    { id: 14, serieId: 6, actorId: 40 },
    { id: 15, serieId: 6, actorId: 41 },
    { id: 16, serieId: 6, actorId: 42 },
    { id: 17, serieId: 7, actorId: 43 },
    { id: 18, serieId: 7, actorId: 44 },
    { id: 19, serieId: 7, actorId: 45 },
    { id: 20, serieId: 8, actorId: 46 },
    { id: 21, serieId: 8, actorId: 47 },
    { id: 22, serieId: 8, actorId: 48 },
    { id: 23, serieId: 9, actorId: 49 },
    { id: 24, serieId: 9, actorId: 50 },
    { id: 25, serieId: 9, actorId: 1 },
    { id: 26, serieId: 10, actorId: 2 },
    { id: 27, serieId: 10, actorId: 3 },
    { id: 28, serieId: 10, actorId: 4 },
    { id: 29, serieId: 11, actorId: 5 },
    { id: 30, serieId: 11, actorId: 6 },
    { id: 31, serieId: 11, actorId: 7 },
    { id: 32, serieId: 12, actorId: 8 },
    { id: 33, serieId: 12, actorId: 9 },
    { id: 34, serieId: 12, actorId: 10 },
    { id: 35, serieId: 13, actorId: 11 },
    { id: 36, serieId: 13, actorId: 12 },
    { id: 37, serieId: 13, actorId: 13 },
    { id: 38, serieId: 14, actorId: 14 },
    { id: 39, serieId: 14, actorId: 15 },
    { id: 40, serieId: 14, actorId: 16 },
];

export const crew = [
    {
        id: 1,
        fullname: "Steven Spielberg",
        role: "Director",
        description: "A renowned filmmaker known for iconic films such as 'Jurassic Park' and 'E.T.'.",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
        debut: "1971",
    },
    {
        id: 2,
        fullname: "Christopher Nolan",
        role: "Director",
        description: "Director known for his work on 'Inception' and 'The Dark Knight' trilogy.",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
        debut: "1998",
    },
    {
        id: 3,
        fullname: "Roger Deakins",
        role: "Cinematographer",
        description: "Celebrated cinematographer recognized for his work on 'Blade Runner 2049' and '1917'.",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
        debut: "1984",
    },
    {
        id: 4,
        fullname: "Emmanuel Lubezki",
        role: "Cinematographer",
        description: "Award-winning cinematographer known for his work on 'Gravity' and 'Birdman'.",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
        debut: "1991",
    },
    {
        id: 5,
        fullname: "Hans Zimmer",
        role: "Composer",
        description: "A celebrated composer known for scores in 'The Lion King' and 'Inception'.",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
        debut: "1984",
    },
    {
        id: 6,
        fullname: "John Williams",
        role: "Composer",
        description: "A legendary composer known for 'Star Wars', 'Jurassic Park', and 'Harry Potter'.",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
        debut: "1958",
    },
    {
        id: 7,
        fullname: "Quentin Tarantino",
        role: "Writer",
        description: "Writer and director known for 'Pulp Fiction' and 'Kill Bill'.",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
        debut: "1992",
    },
    {
        id: 8,
        fullname: "Aaron Sorkin",
        role: "Writer",
        description: "Known for his distinctive dialogue in 'The West Wing' and 'The Social Network'.",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
        debut: "1988",
    },
    {
        id: 9,
        fullname: "Denis Villeneuve",
        role: "Director",
        description: "Critically acclaimed director known for 'Arrival' and 'Dune'.",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
        debut: "1998",
    },
    {
        id: 10,
        fullname: "Greta Gerwig",
        role: "Director",
        description: "Director and writer known for 'Lady Bird' and 'Little Women'.",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
        debut: "2006",
    },
    {
        id: 11,
        fullname: "Rachel Morrison",
        role: "Cinematographer",
        description: "Known for her work on 'Mudbound' and 'Black Panther'.",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
        debut: "2004",
    },
    {
        id: 12,
        fullname: "Howard Shore",
        role: "Composer",
        description: "Composer for 'The Lord of the Rings' and 'The Departed'.",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
        debut: "1979",
    },
    {
        id: 13,
        fullname: "Lynn Shelton",
        role: "Director",
        description: "Director of indie films like 'Humpday' and 'Your Sister's Sister'.",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
        debut: "2006",
    },
    {
        id: 14,
        fullname: "Wally Pfister",
        role: "Cinematographer",
        description: "Known for his cinematography on 'Inception' and 'The Dark Knight'.",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
        debut: "1990",
    },
    {
        id: 15,
        fullname: "Nora Ephron",
        role: "Writer",
        description: "Screenwriter and director of romantic comedies like 'When Harry Met Sally'.",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
        debut: "1983",
    },
    {
        id: 16,
        fullname: "Spike Lee",
        role: "Director",
        description: "Known for films that address race relations like 'Do the Right Thing'.",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
        debut: "1986",
    },
    {
        id: 17,
        fullname: "Robert Richardson",
        role: "Cinematographer",
        description: "Worked on 'Inglourious Basterds' and 'Shutter Island'.",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
        debut: "1985",
    },
    {
        id: 18,
        fullname: "Trent Reznor",
        role: "Composer",
        description: "Composer for films such as 'The Social Network' and 'Gone Girl'.",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
        debut: "2008",
    },
    {
        id: 19,
        fullname: "Sofia Coppola",
        role: "Director",
        description: "Director known for 'Lost in Translation' and 'The Virgin Suicides'.",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
        debut: "1999",
    },
    {
        id: 20,
        fullname: "Michael Giacchino",
        role: "Composer",
        description: "Known for his work on Pixar films and 'Jurassic World'.",
        photoSrc: "http://localhost:4000/images/placeholder.jpg",
        photoSrcProd: "https://movielandia-avenger22s-projects.vercel.app/images/placeholder.jpg",
        debut: "1997",
    },
];

export const crewMovies = [
    { id: 1, movieId: 1, crewId: 1 },
    { id: 2, movieId: 1, crewId: 3 },
    { id: 3, movieId: 1, crewId: 5 },
    { id: 4, movieId: 1, crewId: 11 },
    { id: 5, movieId: 2, crewId: 2 },
    { id: 6, movieId: 2, crewId: 4 },
    { id: 7, movieId: 2, crewId: 6 },
    { id: 8, movieId: 2, crewId: 12 },
    { id: 9, movieId: 3, crewId: 7 },
    { id: 10, movieId: 3, crewId: 8 },
    { id: 11, movieId: 3, crewId: 9 },
    { id: 12, movieId: 3, crewId: 13 },
    { id: 13, movieId: 4, crewId: 10 },
    { id: 14, movieId: 4, crewId: 1 },
    { id: 15, movieId: 4, crewId: 3 },
    { id: 16, movieId: 4, crewId: 14 },
    { id: 17, movieId: 5, crewId: 2 },
    { id: 18, movieId: 5, crewId: 4 },
    { id: 19, movieId: 5, crewId: 6 },
    { id: 20, movieId: 5, crewId: 15 },
    { id: 21, movieId: 6, crewId: 7 },
    { id: 22, movieId: 6, crewId: 8 },
    { id: 23, movieId: 6, crewId: 9 },
    { id: 24, movieId: 6, crewId: 16 },
    { id: 25, movieId: 7, crewId: 10 },
    { id: 26, movieId: 7, crewId: 1 },
    { id: 27, movieId: 7, crewId: 3 },
    { id: 28, movieId: 7, crewId: 17 },
    { id: 29, movieId: 8, crewId: 2 },
    { id: 30, movieId: 8, crewId: 4 },
    { id: 31, movieId: 8, crewId: 6 },
    { id: 32, movieId: 8, crewId: 18 },
    { id: 33, movieId: 9, crewId: 7 },
    { id: 34, movieId: 9, crewId: 8 },
    { id: 35, movieId: 9, crewId: 9 },
    { id: 36, movieId: 9, crewId: 19 },
    { id: 37, movieId: 10, crewId: 10 },
    { id: 38, movieId: 10, crewId: 1 },
    { id: 39, movieId: 10, crewId: 3 },
    { id: 40, movieId: 10, crewId: 20 },
];

export const crewSeries = [
    { id: 1, serieId: 1, crewId: 1 },
    { id: 2, serieId: 1, crewId: 3 },
    { id: 3, serieId: 1, crewId: 5 },
    { id: 4, serieId: 1, crewId: 11 },
    { id: 5, serieId: 2, crewId: 2 },
    { id: 6, serieId: 2, crewId: 4 },
    { id: 7, serieId: 2, crewId: 6 },
    { id: 8, serieId: 2, crewId: 12 },
    { id: 9, serieId: 3, crewId: 7 },
    { id: 10, serieId: 3, crewId: 8 },
    { id: 11, serieId: 3, crewId: 9 },
    { id: 12, serieId: 3, crewId: 13 },
    { id: 13, serieId: 4, crewId: 10 },
    { id: 14, serieId: 4, crewId: 1 },
    { id: 15, serieId: 4, crewId: 3 },
    { id: 16, serieId: 4, crewId: 14 },
    { id: 17, serieId: 5, crewId: 2 },
    { id: 18, serieId: 5, crewId: 4 },
    { id: 19, serieId: 5, crewId: 6 },
    { id: 20, serieId: 5, crewId: 15 },
    { id: 21, serieId: 6, crewId: 7 },
    { id: 22, serieId: 6, crewId: 8 },
    { id: 23, serieId: 6, crewId: 9 },
    { id: 24, serieId: 6, crewId: 16 },
    { id: 25, serieId: 7, crewId: 10 },
    { id: 26, serieId: 7, crewId: 1 },
    { id: 27, serieId: 7, crewId: 3 },
    { id: 28, serieId: 7, crewId: 17 },
    { id: 29, serieId: 8, crewId: 2 },
    { id: 30, serieId: 8, crewId: 4 },
    { id: 31, serieId: 8, crewId: 6 },
    { id: 32, serieId: 8, crewId: 18 },
    { id: 33, serieId: 9, crewId: 7 },
    { id: 34, serieId: 9, crewId: 8 },
    { id: 35, serieId: 9, crewId: 9 },
    { id: 36, serieId: 9, crewId: 19 },
    { id: 37, serieId: 10, crewId: 10 },
    { id: 38, serieId: 10, crewId: 1 },
    { id: 39, serieId: 10, crewId: 3 },
    { id: 40, serieId: 10, crewId: 20 },
];
// #endregion

// #region "Custom script for writting in file and generating stuff"
// const seasons: any = [];
// const episodes: any = [];

// // function formatDate(date) {
// //     const day = (`0${date.getDate()}`).slice(-2);
// //     const month = (`0${date.getMonth() + 1}`).slice(-2);
// //     const year = date.getFullYear();
// //     return `${day}/${month}/${year}`;
// // }

// function replaceImageUrl(url: any) {
//     const urlObj = new URL(url);
//     return `${urlObj.origin}/images/placeholder.jpg`;
// }

// series.forEach((serie) => {
//     const numSeasons = Math.max(1, Math.floor(Math.random() * 2) + 1);

//     for (let seasonNumber = 1; seasonNumber <= numSeasons; seasonNumber++) {
//         const season = {
//             id: seasons.length + 1,
//             title: `Season ${seasonNumber}`,
//             photoSrc: replaceImageUrl(serie.photoSrc),
//             photoSrcProd: replaceImageUrl(serie.photoSrcProd),
//             description: `Description for Season ${seasonNumber} in ${serie.title}.`,
//             trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
//             dateAired: "01/01/2000",
//             ratingImdb: parseFloat((5.0 + Math.random() * 1.5).toFixed(1)),
//             serieId: serie.id,
//         };

//         seasons.push(season);

//         const numEpisodes = Math.max(1, Math.floor(Math.random() * 2) + 1);

//         for (let episodeNumber = 1; episodeNumber <= numEpisodes; episodeNumber++) {
//             const episode = {
//                 id: episodes.length + 1,
//                 title: `Episode ${episodeNumber}`,
//                 photoSrc: replaceImageUrl(serie.photoSrc),
//                 photoSrcProd: replaceImageUrl(serie.photoSrcProd),
//                 trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
//                 duration: Math.max(15, Math.floor(Math.random() * 45) + 1),
//                 description: `Description for Episode ${episodeNumber} of Season ${seasonNumber} in ${serie.title}.`,
//                 dateAired: "01/01/2000",
//                 ratingImdb: parseFloat((5.0 + Math.random() * 1.5).toFixed(1)),
//                 seasonId: season.id,
//             };

//             episodes.push(episode);
//         }
//     }
// });

// const fileContent = `
// export const seasons = ${JSON.stringify(seasons, null, 2).replace(/"([^"]+)":/g, "$1:")};
// export const episodes = ${JSON.stringify(episodes, null, 2).replace(/"([^"]+)":/g, "$1:")};
// `;

// fs.writeFile("data.ts", fileContent, (err) => {
//     if (err) {
//         console.error("Error writing to data.ts file:", err);
//     } else {
//         console.log("data.ts file has been written successfully.");
//     }
// });
// #endregion
